### ISSUE TITLE
Trädstruktur enligt gamla UAT

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#102]
**Beskriv den lösning du önskar**
Johan hade byggt en trädstruktur i "gamla" UAT som försvann när ni splitade miljöerna (tror vi) Fredrik skulle kolla om han kunde kopiera över den till nya UAT? Ni får gärna ge besked, tack.

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Detta är som sagt klart! :) @MonaAdawi
