### ISSUE TITLE
Fel namn som rubrik på störningen (UAT)

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#103]
**Beskriv buggen**
Vi har tidigare ändrat namnstrukturen så namnet ut mot hemsidan ska bli tex "Rödeby" för en störning som #416 som jag precis skapade. Nu heter den Rödebyvägen vilket är fel. Se stängt ärende https://github.com/studio27se/ehub/issues/90
![image](https://github.com/studio27se/ehub/assets/164028902/bf6a06d5-6ccf-499a-9d28-733c6bdc2631)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Detta är en inställning! Du hittar den i modulinställningarna genom att klicka på den berörda kategorin. @monaadawi

**Comment by MonaAdawi** [comment]
Men kom inte det med när vi bestämde att ändra? Det har väl funkat innan? @FredrikElliot

**Comment by FredrikElliot** [comment]
@MonaAdawi 
När jag la över detta till uat sa jag till @johulls att jag inte mindes på vilken nivå ni ville ha era namn, att de nu ligger på den nivån du upptäckt och att han måste ändra i modulinställningarna om det är fel.

Detta är alltså inte fast-programmerat, utan en inställning ni kan göra själva. Jag har nu sänkt antalet steg i namn-skapandet i modulinställningarna för Stadsnät. Men det gäller ju bara för UAT-miljön. När vi lägger över detta i produktion, måste denna inställningar justeras för alla kategorier även där.
