### ISSUE TITLE
Inga notiser

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#105]
**Beskriv buggen**
Hej @FredrikElliot @Kristoffer93 

Jag har lagt ut en driftstörning ref 402 som är en medel kritikalitet. Jag har fått sms och mejl som skapare men det har inte gått ut till någon annan mottagare. Kan ni titta på detta snarast då vi i nuläget inte får ut någon information till våra mottagare.

Hälsningar
Johan

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Supportmail, sms och samtal räcker ;) @johulls
