### ISSUE TITLE
Egen orsakstext uppdaterar bara den långa beskrivningen

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#106]
**Beskriv den lösning du önskar**
När man skriver en egen orsaksbeskrivning, så uppdateras bara den långa beskrivningen. Men det blir tokigt i kommunikationen ut på tex hemsidan. Den måste även uppdatera den korta beskrivningen. Vi har ett exempel live i produktion just nu när infon blir olika i banner och på driftssidan. Se bild 2. Denna är prio Hög och bör ligga med att lösas bland top 5 issues.
![image](https://github.com/studio27se/ehub/assets/164028902/89da8e28-25e6-4f55-ac2c-56dfb00e1d6c)

![image](https://github.com/studio27se/ehub/assets/164028902/cccabf96-5784-4c5c-ad7d-89cf5f0e2ed5)

@johulls

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Detta ligger hos er. Vi skickar med både kort, lång och egen orsakstext i datat som hemsidan får. Det är upp till hanteringen där att sätta rätt text enligt den logik du önskar 👍 
@monaadawi @johulls

Ps. Det är kul att se eHUB användas live!!! Ds.
