### ISSUE TITLE
Påverkat område syns ej i banner

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#107]
**Beskriv den lösning du önskar**
Idag när vi har en störning så framgår inte vilket område som är påverkat i banner/startsidan hemsidan. Se exempel. Det syns när man klickar in på störning dock, i rubriken. Men detta behöver vi åtgärda. Denna får prioplats nr 10
![image](https://github.com/studio27se/ehub/assets/164028902/6439fb85-dff3-43f8-83bf-877ec17e6dad)

@johulls

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Även detta ligger utanför vår räckvidd. En bra tumregel är att om informationen visas någonstans på hemsidan så är det en hantering inom hemsidan som saknas för att visa samma information på fler ställen.
Områden som på¨verkas är driftstörningens namn och detta inkluderas i datat vi skickar över.
@MonaAdawi @johulls
