### ISSUE TITLE
Markera sms-notiser med "UAT" 

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#108]
**Beskriv den lösning du önskar**
Jag har svårt att skilja sms-notiser som kommer från UAT och Prod. Kan vi markera det på nåt sätt så man slipper bli nervös i onödan när ngn skapar test-störningar i UAT? I mailen ser jag i footer att det står "UAT" så där behövs det inte lika mkt :)

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
- [ ] Add notification sender information to bottom of text content
