### ISSUE TITLE
Felmeddelande när jag ska uppdatera störning i UAT

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#109]
**Beskriv buggen**
Skulle testa issue 76+84 och uppdatera objekt i en pågående störning. Men får detta fel och objekt i störningen är också tomma
![image](https://github.com/studio27se/ehub/assets/164028902/96c6eb54-6186-4cea-a4eb-e9b66a1374cc)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Hmm.. Jag behöver nog se lite mer kring loggen för dig. Jag uppdaterade precis https://uat.ehub.se/v2/outage/outage/418
utan problem (se historik).. 
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot se video skickat via sms nu

**Comment by FredrikElliot** [comment]
Det här är nu löst! @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot adderade objekt i denna befintliga störning och sparade och fick grönt Tadaa, men saknar Historikloggen helt o hållet nu ist, se bild:
![image](https://github.com/studio27se/ehub/assets/164028902/ea7f5051-e991-42f0-80af-1faf8c52593f)

**Comment by FredrikElliot** [comment]
Sådär! Nu är historiken tillbaka! @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Thx! Ok att stänga.
