### ISSUE TITLE
Möjlighet att lägga till interna anteckningar i en driftstörning

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#11]
### Beskriv den lösning du önskar
Vi vill ha möjlighet att lägga egna anteckningar på varje driftstörning som inte skickas eller visas nån annanstans än på själva störningen. "Dagboksanteckningar"

### Förslag eller förfrågan
Förfrågan. Estimat önskas.

### Ytterligare sammanhang
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Dubbelkollar bara att ni sett vår fråga, @johulls

**Comment by FredrikElliot** [comment]
Från möte med AFFV: Manuell historik, endast i webbapplikationen.

**Comment by FredrikElliot** [comment]
12 h i estimat.

**Comment by MonaAdawi** [comment]
@FredrikElliot ni har ok på att utveckla denna. Tack.

**Comment by FredrikElliot** [comment]
Vi påbörjar utvecklingen av det

- [ ] https://github.com/studio27se/ehub-backend-api/issues/196
- [ ] https://github.com/studio27se/ehub-app-ionic/issues/421
- [ ] https://github.com/studio27se/ehub-webapp/issues/232

**Comment by FredrikElliot** [comment]
Nu finns en färdig version av interna anteckningar i webbgränssnittet. Dessa distribueras inte till appen eller webintegrationen, utan är endast synliga i webbappen.

**Comment by MonaAdawi** [comment]
Toppen tack! @FredrikElliot

**Comment by MonaAdawi** [comment]
@FredrikElliot öppna gärna denna igen. Jag skulle testa denna nu (borde gjort innan) men kan inte se vart anteckningen hamnar.. Kommer inte under historik. MEN det är ju lite problem på webben så kanske beror på det..

**Comment by FredrikElliot** [comment]
Öppnar igen 👍 @MonaAdawi

**Comment by johulls** [comment]
Jag kan inte spara anteckningar får följande fel 
 
[Fel.docx](https://github.com/studio27se/ehub/files/14881463/Fel.docx)

**Comment by FredrikElliot** [comment]
Vi har rättat felet och @johulls har bekräftat att det funkar! Stänger issuet.
