### ISSUE TITLE
Uppdatering på bef driftstörning visas ej i historik + notis

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#110]
**Beskriv buggen**
Jag skapade en ny störning och gjorde lite uppdateringar på den (se historik). Sista uppdateringen jag gjorde valde jag att visa på webben OCH ändra status. Tryckte spara. Men bara visa på webben syns i historiken och den nya statusen har inte skickats ut med notiserna, som den ska. 
![image](https://github.com/studio27se/ehub/assets/164028902/cb54b43a-2b2a-47bb-ad09-a1a60860924f)

Hemsidan har dock uppdaterats med rätt status.
![image](https://github.com/studio27se/ehub/assets/164028902/b038c331-8031-4bd8-97d3-e9b660d4115f)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
@MonaAdawi 
Denna buggen är nu löst!

**Comment by MonaAdawi** [comment]
@FredrikElliot verkar funka nu. Ok att stänga.
