### ISSUE TITLE
Titel uppdateras inte med "mfl"

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#111]
**Beskriv buggen**
Jag vet inte om detta är en bugg men jag lägger den som det nu.
När jag skapar en störning med objekt från olika områden direkt (Rödeby, Nättraby, Jämjö tex) så blir Titel Rödeby mfl = rätt.
Men om jag skapar en störning med bara objekt från tex Rödeby först, och sen uppdaterar störningen med objekt från Nättraby också, så heter störningen fortfarande Rödeby och mfl kommer inte med = fel. Det skulle vara bra om titel uppdateras med "mfl" när detta sker.
![image](https://github.com/studio27se/ehub/assets/164028902/b26f3320-bf21-4765-8e38-575d1148d916)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Det är inte en bugg och jag tycker att ni kanske ska fundera på om ni vill ändra. (Det är såklart möjligt!) Men det gör det ju lite knepigt att följa progressen för en driftstörning om titeln ändras "hela tiden", för de som inte har ett id-nummer att koppla ihop. Titeln som den är nu är konstant. Jag justerar detta till en förbättring så kan vi ju kika på det framöver.
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot jag förstår. Men på nåt sätt måste det framgå att nu är fler områden berörda av störningen.. Det är ju knepigt hur som helst även om det bara står "Rödeby mfl" kan jag tycka. För om jag bor i Nättraby så kommer jag inte kunna se att jag är drabbad nånstans. Så antingen får man ju skapa fler likadana störningar fast olika områden/objekt, eller se över hur vi informerar om vilka områden som är berörda.. Denna är viktig tycker jag.
@johulls får säga vad han tycker när han är tillbaka.

**Comment by FredrikElliot** [comment]
Yes, men det här behöver också funderas på utifrån kontexten av de andra AOna. Eventuellt skulle man kunna implementera ytterligare data om vilka nimngivande objekt som inkluderas i störningen.
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot ja precis att addera mer data/info i själva kommunikationen av störningen, skulle kunna se ut så här typ: 
![image](https://github.com/studio27se/ehub/assets/164028902/a1cb1e45-cfc7-4459-ad5b-4a11b3dd8861)

Då kan ju Titel styras på ett sätt, men mer info skickas med till hemsidan, notiser osv.
Och är det bara Rödeby, då står det bara Rödeby där..

**Comment by FredrikElliot** [comment]
Härifrån kommer nog det jag mailade om. Eller ja, mitt svar på din fråga, @monaadawi. Stänger denna diskussionen eftersom vi har ett äldre ärende gällande samma (#73) oavsett.
Även dublett i #135.
