### ISSUE TITLE
Ändrad kritikalitet genererade inte notis?

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#112]
**Beskriv buggen**
Jag e osäker på om detta är en bugg...
Jag uppdaterade en befintlig störning från Låg till Hög kritikalitet (#424), men det genererade inte en notis till mig, är det förväntat eller borde det skickats ut? Och om detta är förväntat, skickas det då ut en notis till Målgrupper som tex bara villa ha Höga störningar? 
Man fick inte första notisen när störningen var klassad som Låg, men nu när den trappats upp till Hög så ska ju dom få. Kan man se om det funkar så?

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Detta var samma bugg som #110 och är nu löst!
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot ok att stänga jag har testat.
