### ISSUE TITLE
Objekt har raderats/nollställts när jag ska avsluta störningar

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#113]
**Beskriv buggen**
jag försöker avsluta störningar i listan i UAT (tex #416 men har kollat fler) och klickar i den sista statusen. Men får detta meddelande när jag trycker "Spara"
![image](https://github.com/studio27se/ehub/assets/164028902/4d7cf21c-65e5-44dc-ba1c-8a2a64dc0023)

När jag kollar i objektlistan så ser jag att inget är valt. Men varför har dom försvunnit? När jag klickar i ett objekt och försöker avsluta och spara igen så funkar det (gjorde så på #415). Men detta är fel. Objekten som är valda från början för störningen borde vara ifyllda och inte försvinna.

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
@MonaAdawi 
Den här är lite klurig. Jag TROR att det som har hänt är att sidan helt enkelt inte riktigt varit färdigladdad med all data innan det har gjorts ändringar. Jag hittade också en liten bugg som kaaan ha hjälp till. Men jag hittar inget som är en självklar förklaring till ditt problem. 
För att: problemet du har nu är att din driftstörnings berörda objekt är en väg... inte en ASR. Och det.. ska liksom inte vara möjligt. 

Det jag har gjort för att undvika detta framöver är att jag har helt enkelt låst vissa delar av sidan tills det att allt är inläst. Dvs, det går inte att trycka på spara-knappen exempelvis, och trädet visas inte alls förrän det är helt klart (En laddningsanimation visas under tiden).

Jag har dessutom lagt upp ett internt ärende för att backendet (eHUB-motorn) ska sparka bakut om man försöker spara/skapa en driftstörning som innehåller några objekt som inte är löv/bottenobjekt. Det är inte riktigt på plats än, men ska i det här fallet mest agera som hängslen och livrem utifall mina försiktighetsåtgärder i webappen inte funkar.

**Comment by FredrikElliot** [comment]
@MonaAdawi 
Alltså: Testa gärna på nya driftstörning där så att det funkar. De gamla kan ju ha lite fel i datat verkar det som.. Jag kan rensa, om du vill?

**Comment by MonaAdawi** [comment]
@FredrikElliot avslutade 2 nyare störningar och då funkar det. Du kan stänga denna.
