### ISSUE TITLE
Avsluta störning i UAT appen frågar inte efter sluttid

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#115]
**Beskriv buggen**
När jag avslutar störningar på webben så kommer en pop up med frågan om faktiskt sluttid. När jag ska avsluta en störning i appen så kommer ingen fråga om faktiskt sluttid. När jag valt den sista statusen så dröjer det först några sekunder, sen avslutas störningen utan att den frågar mig om sluttid. 

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Kravet var att i appen som är mer direkt ute på fältet sätts sluttiden automatiskt när man väljer den avslutande statusen. I webbappen som är mer administrativ skulle man få möjlighet att ändra tiden själv.
Jag stänger den här issuen, så kan ni öppna en ny om ni kommit fram till att ni vill ha det annorlunda :) - För jag gissar att det isf inte blir förrän efter sommaren som ett sådan beslut kan tas.
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot tack för update jag hade glömt det!
