### ISSUE TITLE
dubbla notiser med olika innehåll?

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#116]
**Beskriv buggen**
Avslutade en störning i UAT appen #426 och fick dubbla notiser (1 min mellanrum) med olika statusar. Tror jag har identifierat denna förut för jag minns att den väljer lång beskrivning på den ena och kort på den andra. Minns inte vad er lösning var eller om ni har löst det?
![image](https://github.com/studio27se/ehub/assets/164028902/417ebf0f-067e-47f1-9d27-e766a720c17b)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Hehe snaaaart semester! Vi pratade om denna i måndags :) Du hittar den i #92 
@MonaAdawi
