### ISSUE TITLE
Rensa/töm sluttid på akut störning i appen

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#118]
**Beskriv buggen**
Oklart om detta är en bugg eller om jag inte vet hur man gör eller om det är en förbättring..
men jag kan inte hitta hur jag rensar/tömmer sluttiden på en akut störning i appen? I webben finns en tydlig knapp som heter "Töm". det borde finnas i appen också givetvis. Eller går det att tömma fältet men jag inte vet hur man gör bara? 
![image](https://github.com/studio27se/ehub/assets/164028902/f5ad2e80-f7cc-4508-b06b-f061bb92de93)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Det här är nog en legacy från att ni från början ville att förväntad sluttid alltid skulle anges. Det är väl eventuellt en förbättringsgrej.. Men jag lägger det som en bugg. Happy summer!
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot @johulls
Jag testade denna och stötte på en sak:
1. Jag skapar en ny akut störning i appen och då efterfrågas inte förväntad sluttid. Så jag matar bara in starttid och ingen sluttid och fyller i resten och sparar sen. 
3. Sen går jag in och uppdaterar med en sluttid. Sparar. 
4. Sen går jag in på störningen igen och rensar datum/tid och vill lämna fältet tomt igen. Men då får jag inte spara utan en sluttid. Jag vet inte om flödet blir lite motsägelsefullt så här...? Vad tycker ni? Men det jag beskriver här kanske inte kommer hända ens och isf får Johan kliva in och säga "strunt i det" :)

**Comment by FredrikElliot** [comment]
Yes! Sorry, den här är inte klar för test än. Vi har bestämt att vi tar kostnaden för den här justeringen, så om ni inte tycker att den känns relevant hoppar vi gärna över det :D Ni kan väl skriva hur ni vill ha det!
@johulls @MonaAdawi

**Comment by MonaAdawi** [comment]
Jag tycker det blir motsägelsefullt som det är just nu. Men @johulls vad tycker du och vad är ett möjligt scenario IRL?

**Comment by johulls** [comment]
Jag kan faktiskt inte riktigt se när man skulle vilja ta bort en slut tid om man väl har fyllt i den. Det man i så fall vill göra är att förändra den tänker jag. @FredrikElliot @MonaAdawi

**Comment by FredrikElliot** [comment]
Tolkar jag det som att den här buggen... inte är en bugg? Utan en feature 😆 
@johulls @MonaAdawi

**Comment by FredrikElliot** [comment]
@MonaAdawi Jag har satt igång arbetet med att avsluta det här ärendet i mobilappen igen :)

**Comment by MonaAdawi** [comment]
@FredrikElliot godkänd 10 sep.
