### ISSUE TITLE
Uppdaterad sluttid sparas inte på störning

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#119]
**Beskriv buggen**
Jag öppnade en pågående akut störning i UAT appen. Gjorde en statusuppdatering varpå en pop up dyker upp som ber mig uppdatera sluttid. Jag väljer att rensa fältet för jag vet inte sluttid "längre". Jag sparar och får "godkänt" i tron om att störningen nu har rensat/tömt sin sluttid. Men det gör den inte. Se film som ligger här: https://affarsverken.sharepoint.com/:v:/r/sites/Frbttradinformationviddriftavbrott/Delade%20dokument/General/Filmer%20fr%C3%A5n%20ehub/[video-20240711-064147-0f45d9c0.mov](https://affarsverken.sharepoint.com/:v:/r/sites/Frbttradinformationviddriftavbrott/Delade%20dokument/General/Filmer%20fr%C3%A5n%20ehub/video-20240711-064147-0f45d9c0.mov?csf=1&web=1&e=GhvgZh)?csf=1&web=1&e=GhvgZh

1. Eftersom akuta störningar kan ha tomt fält på sluttid så ska ovan scenario funka.
2. Om det inte ska funka att göra så här så ska systemet inte ge mig godkänt på handlingen jag utför utan borde ge ett felmeddelande med orsak varför den inte kan spara. 

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
3. Klicka på '....'
4. Rulla ner till '....'
5. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
- [ ] [Clearing plannedEnd ("Förväntad sluttid") removed value from data sent to BE](https://github.com/studio27se/ehub-app-ionic/issues/464)

**Comment by MonaAdawi** [comment]
@FredrikElliot denna är samma som #120 va? Isf är den ok att stänga också.

**Comment by FredrikElliot** [comment]
Yes samma! Stänger båda! @MonaAdawi
