### ISSUE TITLE
Möjlighet att välja alla underobjekt till ett objekt i en driftstörning

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#12]
**Beskriv den lösning du önskar**
När man arbetar med val av objekt i en driftstörning, både under skapandet och när man ändrar, så ska man kunna välja alla objekt under ett specifikt objekt. Istället för att slippa gå in i det objektet och sedan klicka på alla underobjekt.

**Förslag eller förfrågan**
Förfrågan. Estimat önskas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Vi estimerar att vi skulle behöva ca 16 h för att implementera det här.
@johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot beslut Affv: kan vänta till efter lanseringen för Stadsnät.

**Comment by MonaAdawi** [comment]
@FredrikElliot vi upplever att denna är löst.... Det funkar som vi vill ha det iaf :)

**Comment by FredrikElliot** [comment]
@MonaAdawi Observera att det här önskemålet gäller mobilappen. Återkom om vi ska stänga ändå :)

**Comment by MonaAdawi** [comment]
Bra att du sa @FredrikElliot @johulls vad säger du?

**Comment by johulls** [comment]
@FredrikElliot @MonaAdawi  Vi behöver den funktionen i appen absolut nästan viktigare där. Tänker satt den är hög med lägst prio av de som är klassade som höga.

**Comment by FredrikElliot** [comment]
### Kravbeskrivning
När en användare skapar eller redigerar en driftstörning i mobilappen ska det vara möjligt att på navigeringsnivå markera en navigeringsgrupp, för att automatiskt välja alla underobjekt som tillhör den gruppen. 

Ex.
-- Stad
-- -- Område
-- -- -- Underobjekt 1
-- -- -- Underobjekt 2

Området kan markeras i appen, vilket resulterar i att både Underobjekt 1 och Underobjekt 2 väljs som påverkade enheter.

### Kopplade utvecklingsissues

- [ ] Enable select-all-below in entity tree selection

**Comment by FredrikElliot** [comment]
@johulls Kan du bara dubbelkolla om kravbeskrivningen är som ni tänkt er och i sådana fall ge en tumme upp ✅

**Comment by FredrikElliot** [comment]
> [@FredrikElliot](https://github.com/FredrikElliot) [@MonaAdawi](https://github.com/MonaAdawi) Vi behöver den funktionen i appen absolut nästan viktigare där. Tänker satt den är hög med lägst prio av de som är klassade som höga.

Jag har förresten flyttat upp denna i prioritet. Nu ligger den sist av de hög-prioriterade.
@johulls @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Johan och jag säger tummen upp på nya kravbeskrivningen

**Comment by FredrikElliot** [comment]
Detta kan testas i v.1.4.0
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot jag har testat nu och det funkar att välja alla objekt genom att dra höger. Denna är ok att stänga.
