### ISSUE TITLE
Kan spara med tomt fält i starttid = fel

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#120]
**Beskriv buggen**
detta problem påminner om issue 119 och kanske e samma, men jag gör ändå en ny ifall det inte är det. Jag uppdatera en störning med ny status och pop up ber mig välja förväntad starttid, men jag lämnar fältet tomt och sparar. Jag får grönt ok, men jag ska inte kunna spara alls utan ange en tid i det (båda) fältet. Och en förväntad starttid finns angivet när jag kollar notiserna och historikloggen säger inget om ändrad/tom starttid. Se film: https://affarsverken.sharepoint.com/:v:/r/sites/Frbttradinformationviddriftavbrott/Delade%20dokument/General/Filmer%20fr%C3%A5n%20ehub/[video-20240711-113125-39dfd19e.mov](https://affarsverken.sharepoint.com/:v:/r/sites/Frbttradinformationviddriftavbrott/Delade%20dokument/General/Filmer%20fr%C3%A5n%20ehub/video-20240711-113125-39dfd19e.mov?csf=1&web=1&e=y2NBaT)?csf=1&web=1&e=y2NBaT

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Yes! Samma bugg som #119 Det kommer snart en ny uppdatering
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot denna uppdatering är inte heller gjord innan semester?

**Comment by FredrikElliot** [comment]
Yes, det är löst i 1.4.5 som ännu inte är släppt till er.

**Comment by MonaAdawi** [comment]
@FredrikElliot testad nu. ok att stänga.
