### ISSUE TITLE
Felmeddelande när jag vill byta starttid på en pågående störning

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#121]
**Beskriv buggen**
Felmeddelande när jag vill byta starttid på en pågående störning.
Se film här: https://affarsverken.sharepoint.com/:v:/r/sites/Frbttradinformationviddriftavbrott/Delade%20dokument/General/Filmer%20fr%C3%A5n%20ehub/[video-20240711-114445-5464b45a.mov](https://affarsverken.sharepoint.com/:v:/r/sites/Frbttradinformationviddriftavbrott/Delade%20dokument/General/Filmer%20fr%C3%A5n%20ehub/video-20240711-114445-5464b45a.mov?csf=1&web=1&e=YyJJLP)?csf=1&web=1&e=YyJJLP

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Yes! Detta är redan plockat i en nyare version - snart i er TestFlight!
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot jag testade denna nu men det är samma fel. (jag har loggat in, loggat ut, väntat, loggat in, osv.)

**Comment by MonaAdawi** [comment]
@FredrikElliot ok sånt kommer inte jag ihåg! Totalt tomt här :-P Jag gick bara på din senaste kommentar ovan :)

**Comment by MonaAdawi** [comment]
@FredrikElliot på mötet i tisdags uppfattade jag det som att ni skulle släppa ny version ganska direkt? Men jag testar ovan och det funkar fortfarande inte. När kommer ny version?

**Comment by FredrikElliot** [comment]
@monaadawi den är inskickad för review av Apple som borde ha rullat igenom den innan helgen. Det är version 1.4.5, så innan du ser det i din mobil är det inte någon mening att testa direkt..

**Comment by MonaAdawi** [comment]
@FredrikElliot ok jag avvaktar #otålig

**Comment by MonaAdawi** [comment]
@FredrikElliot denna funkar nu. Ok att stänga.
