### ISSUE TITLE
Byte av objekt (skärgårdstrafiken) på pågående störning uppdateras inte i titel

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#124]
**Beskriv buggen**
Jag skapade en störning # 441 på Skärgård och valde Båt Gåsefjärden som objekt. Sparade och allt kom ut på hemsidan och i notiser som det skulle. Men sen bytte jag objekt från Båt till Linje Fisktorget -Stenshamn Bryggstopp Trummenäs. Titel på störning uppdateras inte då utan heter fortfarande Gåsefjärden. Även i notiser o hemsidan. Är det förväntat? 

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Mja, eller det i alla fall samma diskussion som i #73 där vi pratar om huruvida titeln ska ändras om objekten ändras. Jag tänker att jag stänger detta ärendet och lägger till din kommentar i det andra. Det är dock markerat med fas2. @MonaAdawi
