### ISSUE TITLE
Tidigare godkänd issue är fel igen: Ta bort "Berörda enheter" i alla notiser

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#125]
**Beskriv buggen**
Issue 76 är closed och godkänd och har funkat. https://github.com/studio27se/ehub/issues/76 
Men i senaste notiserna som skickats ut i samband med skarp driftstörning så syns berörda enheter i notiserna igen. Kan ni kolla varför det blivit så och fixa det så snart som möjligt tack.
@johulls 

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Kan du ge oss ett driftstörningsnummer där det ska ha blivit så? Skulle vi också kunna få vet ungefär när dessa notiser mottogs?
-- Fredrik
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Se störning 418 (2 sep kl 10-tiden) och störning 420 (3 sep hela kvällen)

**Comment by FredrikElliot** [comment]
Gjorde lite research i våra kodändringar och det här är löst - på UAT. Vi inte gjort en release sen i maj så det kommer komma med i nästa eHUB-motor-release. Jag skriver till dig separat om våra releaseplaner de kommande veckorna!
@MonaAdawi 
Men för nu stänger jag denna issuen :)
