### ISSUE TITLE
PROJEKT-3: Lägg till mottagare i mottagargrupp ifrån en lista istället för fritext

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#13]
**Beskriv den lösning du önskar**
Att man la upp mottagare på ett ställe och sedan knyter dom till en eller flera mottagargrupper.

Det ska finnas en lista med mottagare där administrationen av möjliga mottagare sker. Det ska gå att titta på och ändra informationen för en specifik mottagare härifrån. Det ska också gå att lägga till mottagaren i alla mottagsgrupper.

Från en mottagargrupps sida ska man också kunna lägga till mottagare, men istället görs det med sök på mottagare från ovan nämnda lista.

**Förslag eller förfrågan**
Förfrågan. Estimat krävs.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by MonaAdawi** [comment]
@FredrikElliot beslut Affv: kan lösas så snart som möjligt efter lanseringen för Stadsnät.

**Comment by FredrikElliot** [comment]
Inser nu att titeln på det här issuet är motsägelsefullt enligt vad jag minns från våra diskussioner.
Jag undrar om det inte är så att:
- Driftstörningsmottagare läggs till som individer i en lista.
- Varje mottagare kan lägga till sitt mobilnummer och/eller epost.
- Varje mottagare kan själv specificera vilka kategorier den vill ha kommunikation kring, för vilka nivåer. Detta sker alltså inte på en mottagargrupp-nivå, utan på individnivå.
- För enklare översikt skulle vi kunna lägga till möjligheten att tagga mottagare med egen-definierade taggar. Exempelvis "Ledningsgrupp" "Leverantör". Så att man kan söka på dessa taggar och få upp mottagre med den taggen. Jag tänker dessutom att man ska kunna sätta mer än en tagg per person, eftersom man kanske ingår både i ett AO och en mindre gruppering eller liknande.

Alltså: Alla inställningar som idag görs på gruppnivå skulle i sådana fall göras på individnivå. 

Tillägg: vi SKULLE kunna kika på multi-redigering. Dvs. att man kan typ checka i ett gäng användare och göra en massredigering på dem för enklare hantering. Men det tycker jag absolut är ett mycket senare steg.

Tanka? @MonaAdawi @johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot vi har bokat internt möte för att diskutera och återkomma med kravspec till er (v.40)

**Comment by FredrikElliot** [comment]
Här kommer wireframes för hur interfacet kan se ut. De är skisser så detaljer kan såklart justeras, men så att vi fångar den generella känslan fångas.

Bild 1: Mottagarlista - Här kan alla mottagare listas med möjlighet att själv välja vilka kolumner man vill se när det kommer till kategorierna, via knapparna ovanför listan.
<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGhuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--627c56db5762bb6e07a663ec2df99d7483d51317/image.png" alt="image.png" />

Bild 2: Multimottagarredigering - När användarnas checkbox klickas i tänds knapper för redigering, och man kan applicera ändringar för alla användare man har kryssat i samtidigt. Observera att man endast kan redigera kategori/notisinställningar och inte epost/mobilnummer/namn. 
<img width="1312" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b7e3fae7ce92e339c6710346c608caaca47b047/image.png" alt="image.png" />

Hör av er med era tankar! @monaadawi @johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot tagga denna med: Projekt

**Comment by MonaAdawi** [comment]
@FredrikElliot vi tittar, tänker och återkommer

**Comment by MonaAdawi** [comment]
@FredrikElliot kan du döpa rubriken med inledningen: Projekt-3: Tack

**Comment by FredrikElliot** [comment]
Anteckningar från möte med Affärsverken: Lägg till checkruta för att kryssa i alla mottagare som visas i tabellen (just nu) samtidigt. Vi fetstilar räknare för antal mottagare som ska _preferensredigeras_.

**Comment by MonaAdawi** [comment]
@FredrikElliot och avdelning skulle komma med från AD? Eller sa vi inte så nu.. (snurrar jag till det?)

**Comment by FredrikElliot** [comment]
@monaadawi det stämmer! Och gällande kryssrutorna kommer vi inte kunna implementera en "alla alla" markering. Det är för stor risk för fel då :)

**Comment by FredrikElliot** [comment]
**Inte godkänd!**
Fönstret autojusteras inte i Affv UAT, samt ger 404-fel på export.

**Comment by MonaAdawi** [comment]
@FredrikElliot 
Test 5 dec: konstiga vyer och export funkar ej (oavsett hur många AO jag kryssat i)
![image](https://github.com/user-attachments/assets/5bedd40e-3028-40c8-855e-f79639956fd2)
