### ISSUE TITLE
Mer information om valt objekt i driftstörningar (tex Rödeby mfl.)

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#130]
**Beskriv den lösning du önskar**
Vi vill utöka informationen på hemsidan med mer information vilka dom påverkade objekten är. Tex om störningar pågår i Rödeby, Jämjö, Nättraby, så ska detta skrivas ut i den utökade infon på hemsidan och mail (INTE i sms dock). Rubriken fortsätter att heta "Rödeby mfl." Denna är extra viktig för Skärgårdstrafiken. 
Denna har en hög prio. Hur går vi vidare? Kan ni lämna estimat eller ska vi samla oss kring kravspec/era frågor till oss först?

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
- Om rubriken är döpt efter ett område som inte längre är drabbat, ska den ändras?

I övrigt sparar vi en lista (i en JSON-sträng) på alla namngivande objekt som är föräldrar till berörda driftstörningsobjekt, samt en indikation på om de fortfarande är del i störningen, eller avklarade.

**Comment by MonaAdawi** [comment]
@FredrikElliot jobbar ni med denna? Det vore jättebra om ni kan jobba med denna och bli klara så snart möjligt? Hur ser det ut för er?

**Comment by FredrikElliot** [comment]
@MonaAdawi 
Om du minns från igår nämnde jag att denna var det enda förändringen ni kommer behöva testa när vi nu gör nästa test-release, redo för test på fredag 😉

**Comment by MonaAdawi** [comment]
@FredrikElliot tack va bra.

**Comment by FredrikElliot** [comment]
Bekräftad av Christian! Stänger issuet.
