### ISSUE TITLE
Svaren på kritikalitetsfrågor nollställs när jag väljer nya objekt på bef störning

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#136]
**Beskriv buggen**
Svaren på kritikalitetsfrågor nollställs när jag väljer nya objekt på bef störning. jag har för mig att vi redan löst denna men jag kan inte hitta den i vår historik eller closed..

Om du hittar en sån issue får du slå ihop med denna. Men om den är stängd så har iaf felet återuppstått :(

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Hmm.. Jag kan inte återskapa det här problemet.. 
Vilken störning gäller det här? Gäller det app eller webapp? 
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot senast på 488

**Comment by MonaAdawi** [comment]
@FredrikElliot jag hittade problemet nu. Jag har haft en störning 488 där jag först hade valda objekt på bryggstopp, och sen tog jag bort alla bryggstopp och valde båtar ist. Vilket innebär att det en liten stund inte är några valda objekt alls i störningen. Och det är då frågorna nollas. Detta kanske aldrig kommer hända eftersom man sällan tar bort alla sina valda objekt i en störning... vad tror du?

**Comment by FredrikElliot** [comment]
Nej, då låter det ju som att störningen är avslutad istället - eller att det skulle varit en ny registrering. Om inga rutor är ikryssade vet systemet inte längre vilka kritikalitetsfrågor som ska användas eftersom de tillhör kategorin. Därför nollställs den delen idag, om du kryssar ur alla rutor.
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot då kan vi stänga denna :)
