### ISSUE TITLE
Faktiskt sluttid finns med trots att inget angets

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#14]
**Beskriv buggen**
Gäller bara web i mailet finns faktisksluttid trots att man inte har definerat någon. Den sätter samma som faktisk starttid

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Vi skulle behöva lite mer information, då vi inte kan återskapa det här felet. Återkom gärna med driftstörningsnummer/namn samt mailet så vi kan kolla på ett exempel.

**Comment by johulls** [comment]
Jag kan inte heller återskapa det längre provade att göra en ny exakt som när jag hitta det men jag kan inte återskapa det.
Jag skickar i alla fall med mailet så ser ni vad jag menar.

//Johan

Från: Fredrik Elliot ***@***.***>
Skickat: den 7 mars 2024 13:56
Till: studio27se/ehub ***@***.***>
Kopia: Johan Ullström ***@***.***>; Mention ***@***.***>
Ämne: Re: [studio27se/ehub] Faktiskt sluttid finns med trots att inget angets (Issue #14)


@johulls<https://github.com/johulls> Vi skulle behöva lite mer information, då vi inte kan återskapa det här felet. Återkom gärna med driftstörningsnummer/namn samt mailet så vi kan kolla på ett exempel.

**Comment by FredrikElliot** [comment]
Mailet:
Från: 
Skickat: den 5 mars 2024 19:06
Till: Johan Ullström 
Ämne: Ny driftstörning

Ny driftstörning
#132 - Idrottsvägen

Kategori: Stadsnät
Kritikalitet: Hög
Status: Ny driftstörning
Planerad driftstörning: Nej
Orsak: Okänd
Faktisk starttid: 2024-03-05 19:03:00
Faktisk sluttid: 2024-03-05 19:03:00

Läs mer: [LÄNK]

**Comment by FredrikElliot** [comment]
Jag ser att driftstörning 132 faktiskt har både starttid och sluttid angivna och att det är samma (ovan) värde på båda. Min gissning är någon har klickat i sluttidfältet. Så fort man klickar (även om man inte väljer en tid, utan klickar utanför rutan) så läggs "nu" in som tid. Därför finns knappen "töm" precis brevid rutan. 

@johulls , kan vi stänga issuen?

**Comment by FredrikElliot** [comment]
Bekräftat stängning med Johan.
