### ISSUE TITLE
Alla störningar som skapas i Ehub UAT Webb får Låg kritikalitet

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#141]
**Beskriv buggen**
När jag skapar en störning i UAT och svarar på kritikalitetsfrågor som SKA generera Hög kritikalitet, så blir ändå resultatet Låg. Gäller oavsett vilket AO/Kategori jag väljer. 
Obs! I appen funkar det som det ska, dvs det blir rätt kritikalitet. 
![Image](https://github.com/user-attachments/assets/1ee8d105-7d58-4d39-b883-8722056364af)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by MonaAdawi** [comment]
Nu verkar det funka på webben men nu är det fel i appen ist. Får detta felmeddelande:
![Image](https://github.com/user-attachments/assets/9493abaf-db9d-4506-89cd-7a17227c6948)

**Comment by FredrikElliot** [comment]
@MonaAdawi Kan du prova igen? Jag kan inte återskapa ditt fel. Vilka val gör du för att nå detta felet?

**Comment by MonaAdawi** [comment]
Fel i appen. Jag går in i en kommande planerad störning och byter svar i kritikalitetsformulär i appen. Den skiftar status från Låg till Hög (=fel) och jag får även ett felmeddelande. Men tittar man noga så tar den inte mitt nya svar i formuläret. Jag vill byta från Lågspänningskund till Högspänning. Jag kan göra det och ser att den skiftar till Hög status. Men när jag trycker Spara får jag fel och den skiftar tillbaka till Lågspänning. Se film

https://github.com/user-attachments/assets/620881ad-76b6-4e25-aac3-700acb0b2f49

**Comment by FredrikElliot** [comment]
Jag kommer flytta din senaste kommentar till ett nytt issue eftersom det är orelaterat problemet med att kritikaliteten inte blir hög/låg enligt bestämd logik. Se issue #143
