### ISSUE TITLE
Introducera "Spara och skapa ny"-alternativ i post-skapande-vyer

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#15]
**Beskriv den lösning du önskar**
När man lägger till nytt driftstörningsobjekt måste man börja om från huvudmenyn på objekt varje gång man skall lägga till nytt objekt. Gör man inte det utan man fyller i nya värden efter att man har sparat även om man ställer sig i översta noden så ändrar den bara på senast tillagda objekt.

**Förslag eller förfrågan**
Förslag

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by MonaAdawi** [comment]
@FredrikElliot den här är viktig men vi kan avvakta tills vi ska implementera Elnät (sep 2024).

**Comment by FredrikElliot** [comment]
Redo för test! @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Nåt är fel med UAT jag kan inte logga in
![image](https://github.com/user-attachments/assets/3b963dde-6583-4901-913e-a8c144529d96)

**Comment by FredrikElliot** [comment]
@MonaAdawi Redo för test!

**Comment by MonaAdawi** [comment]
@FredrikElliot jag är hemskt ledsen jag minns inte riktigt denna så jag vet inte hur jag ska testa :( Kanske @johulls minns bättre?

**Comment by FredrikElliot** [comment]
Det här är på sidan där man skapar ny driftstörningsobjekt @MonaAdawi

**Comment by MonaAdawi** [comment]
@johulls godkände denna muntligt på mötet igår. behöver han skriva nåt här också? @FredrikElliot

**Comment by FredrikElliot** [comment]
Nej, jag stänger denna!
