### ISSUE TITLE
Planerat avbrott byter status till Servicetekniker på plats i området när man klickat på spara. 

### ISSUE THREAD

**Issue by MartinaSkoghTham** [studio27se/ehub#18]
Planerat avbrott byter status till Servicetekniker på plats i området när man klickat på spara. 
Trots att jag aktivt valt statusen Planerat Underhåll. 
Detta gäller då vid skapandet av det planerade under hållet. 
Men går att ändra sedan igen till Planerat underhåll och klicka på spara. 

![image](https://github.com/studio27se/ehub/assets/163012746/cd7a0c90-eca7-494c-8d18-5e3e12a6534a)

- [x] https://github.com/studio27se/ehub-webapp/issues/228

**Comment by FredrikElliot** [comment]
Yes! Bekräftat bugg.
https://github.com/studio27se/ehub-webapp/issues/228

**Comment by FredrikElliot** [comment]
@MartinaSkoghTham
Detta är nu åtgärdat!
