### ISSUE TITLE
Oklarheter sms-notiser när driftsstörning görs via appen 

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#28]
**Beskriv buggen**
En klar och kortfattad beskrivning av vad felet är.
Imorse efter installation av ny version (19 mars) skickades inte sms-notiser ut när jag gjorde PLANERAD störning via appen. Men det kom sms-notis när vi testade störning via webben. Gjorde ingen AKUT vid detta tillfälle.
Testade igen nu under em och då skickas sms-notis ut när jag gör PLANERAD störning via appen. Testade även AKUT störning men då skickas 2 likadana sms ut. Både när jag gör en ny störning, uppdaterar störning och avslutar en störning.

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]
 Iphone iOS 17.3.1

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Hej @MonaAdawi 

Faktorerna som påverkar om och när notiser skickas ut är många. Typ av störning, starttid, kritikalitet, mottagargruppernas kritikalitetsinställningar och tysta tider är alla saker som är med och bestämmer om och när notiser skickas ut.

Skillnaden ni ser mellan mobilappen och webappen handlar nog snarare om vilken typ av störning ni skapar, med vilka starttider, och vilken kritikalitet. Skulle ni kunna dubbelkolla att störningarna du skriver om är störningar inom en tillräckligt hög kritikalitet för att skickas ut och att inte gruppen har tysta tider satta?

**Comment by MonaAdawi** [comment]
@FredrikElliot vi kommer behöva lägga isolerad tid åt att förstå notiserna. Vi ser inte logiken nu. Efter det återkommer vi till er igen.

**Comment by FredrikElliot** [comment]
@MonaAdawi Återkom om ni vill att vi skapar ett flödesschema åt er! Jag stänger detta ärendet så länge.
