### ISSUE TITLE
I appen går det inte att uppdatera orsak bara status

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#29]
Man skall kunna uppdatera orsak 

Fredrik: Enligt inledande diskussioner var detta inget man skulle kunna göra i appen. Det skulle i sådana fall skötas centralt. Behöver detta ändras?

Tagg: Utvärderas efter anv.tester

**Comment by FredrikElliot** [comment]
Hej @MonaAdawi 

På vårt möte i måndags beslutade vi att denna ändringen skulle läggas in omgående. Se senaste kommentaren från mig i #26 .
Betyder detta att ni ändrat er eller blev det bara en dublett?

**Comment by MonaAdawi** [comment]
@FredrikElliot förlåt då blev detta en dublett det var inte meningen :) Vi kan stänga denna då!

**Comment by FredrikElliot** [comment]
Ingen fara! Då gör vi så! :)
