### ISSUE TITLE
2st namnändringar

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#31]
**Beskriv den lösning du önskar**
1. Vi vill byta ut rubriken Kategori till Verksamhetsområde istället. Se bild.
2. Vi vill byta ut knapprubriken Skapa till Registrera istället. Se bild.
![Bild](https://github.com/studio27se/ehub/assets/164028902/98a9421b-2d37-458d-9dc8-9f0cbc0d7275)

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
@MonaAdawi 
Termen `kategori` används för att göra eHUB så generellt som möjligt och öppna upp för fler användningsområden. Driftstörningsmodulen stödjer inte nödvändigtvis uppdelning per verksamhetsområde, utan kan användas med vilken kategoriindelning som helst. Därför ser vi helst att det fortsatt är denna termen som används.


- [ ] Change "Skapa" label on outage creation page

**Comment by FredrikElliot** [comment]
@MonaAdawi 
Nu är ändringen av knappens titel klar. Återkom med era tankar kring vad jag skrev angående `kategori` vs. `verksamhetområde` innan jag stänger issuet.

**Comment by MonaAdawi** [comment]
Nu har jag sett ändringen och vi kan stänga ärendet @FredrikElliot
