### ISSUE TITLE
Bekräfta avsluta ärende vid högsta status

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#32]
När man väljer den högsta/sista statusen för en driftstörning i mobilappen ska man får frågan "Vill du verkligen avsluta driftstörningen?". 
JA
- Statusen uppdateras
- Driftstörningen markeras som avslutad
- Faktiskt sluttid sätts till "nu"
- Användaren förflyttas tillbaka ut till driftstörningslistan

NEJ
- Ingen uppdatering av status

- [x] studio27se/ehub-app-ionic#427

**Comment by FredrikElliot** [comment]
Automatiskt avslutande av driftstörningen är nu implementerat både i webb- och mobilapp. I mobilappen skickas nu användaren tillbaka till driftstörningslistanv om en driftstörning avslutas.
@monaadawi

**Comment by MonaAdawi** [comment]
Tack @FredrikElliot 
Jag försöker tagga Martina och Johan i min kommentar för jag vill att dom testar och bekräftar att det funkar. Ska jag inte kunna tagga andra än dig och Kristoffer här? Kan du tagga dom åt mig isf så dom ser detta också innan vi stänger ärendet. Dom måste bekräfta innan det stängs. Tack!

**Comment by FredrikElliot** [comment]
@MonaAdawi De går att tagga men kommer inte upp i förslagslistan om de inte redan varit delaktiga i issuet. Jag taggar dem!
@johulls @MartinaSkoghTham

**Comment by MonaAdawi** [comment]
Tack @FredrikElliot :)
Dom blir inte taggade nu heller när jag gör det men kanske beror på att dom inte kollat här ännu...
Men hur som helst får ni @johulls @MartinaSkoghTham gärna bekräfta ovan så det är ok att stänga. Tack.
Det kommer gälla alla lösta ärenden, ni måste kolla så det funkar enligt förväntan och sen meddela @FredrikElliot att vi kan stänga. Tagga gärna mig, tack :)

**Comment by FredrikElliot** [comment]
De är taggade! 👍

**Comment by MonaAdawi** [comment]
@johulls kollar denna.

**Comment by johulls** [comment]
Hej @FredrikElliot jag får ingen bekräftelse fråga när jag  avslutar ett ärende.

@MonaAdawi

**Comment by FredrikElliot** [comment]
Det här är helt mitt fel! Jag glömde att ta bort invänta kund och bytte den till redo för test utan att tänka! Sorry! Detta är klart, men inte än releasat i appen. Jag plockar bort Redo för test och lägger en ny kommentar när detta finns att testa (mest troligt på fredag)
@johulls @MonaAdawi

**Comment by FredrikElliot** [comment]
Detta är nu redo för test i v.1.2.5 
@johulls @MonaAdawi

**Comment by FredrikElliot** [comment]
Observa ny version 1.2.7

**Comment by johulls** [comment]
Hej @FredrikElliot!

Jag får en bekräftelse fråga och tiden sätts till nu så det fungerar och denna kan stängas.

//Johan
