### ISSUE TITLE
Ta bort arkiveringsrutan på detaljssidan för driftstörning

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#34]
Det ska inte vara möjligt att arkivera/aktivera en driftstörning manuellt. Detta ska istället alltid göras med en statusförändring.

- [x] studio27se/ehub-webapp#243

**Comment by FredrikElliot** [comment]
@monaadawi,
Nu är arkiverad-rutan borta från driftstörningsdetaljerna. Istället får man frågan angående att sätta tid för faktiskt avslut när man väljer den "sista" statusen (alltså statusen med högst flödesvärde). Sparar man när man gjort detta arkiveras/stängs också driftstörningen.
Liknande beteende implementeras i mobilappen inom kort.

**Comment by MonaAdawi** [comment]
Hej @FredrikElliot jag vill att Martina och Johan bekräftar ändringen innan ärendet är stängt. Kan du tagga dom. Tack.

**Comment by FredrikElliot** [comment]
Absolut! @johulls och @martinaskoghtham
Kan ni bekräfta och stänga issuen om ni är okej med ändringen?

**Comment by johulls** [comment]
Hej!
Ärendet avslutas men jag får aldrig frågan om faktisk avslutstid. När man klickar på spara knappen så händer visuellt ingenting i bakgrunden avslutas ärendet. Detta gäller så väl gamla som nya upplagda  driftstörningar.
