### ISSUE TITLE
Ändringar från användartester

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#36]
Följande ändringar är uppfattade från användartester.

# Buggar
- [x] https://github.com/studio27se/ehub-app-ionic/issues/430
- [x] Historiken för registrering av ett ärende visar json-formatterad QA-data
- [x] Status och Orsak visas som IDn i historiken
- [x] Listan med driftstörningar ska visa nyast överst
- [x] Felaktigt borttagen från tilldelning i driftstörning
- [x] "Fel vid API-anrop" i appen

# Förbättringar
- [x] https://github.com/studio27se/ehub/issues/34
Beskrivning för egen orsakstext
- [x] studio27se/ehub-webapp#249
Nytt filter för att visa "Mina driftstörningar" i driftstörningslistan (webbappen)
- [x] studio27se/ehub-webapp#250

@MonaAdawi, återkom gärna med grönt ljus på ovan förbättringar. Buggen tar vi hand om under tiden.

**Comment by MonaAdawi** [comment]
@FredrikElliot länkarna funkar inte
Får ett 404-fel.

**Comment by MonaAdawi** [comment]
Men jag ser ju inga titlar... @FredrikElliot

**Comment by MonaAdawi** [comment]
Avvakta med 245, 431, 432 tills vi har prioriterat. Men lägg dom gärna i listan med våra samlade uppgifter fast med en tagg "inväntar kund". Tack.

**Comment by FredrikElliot** [comment]
Vi har precis insett att titlarna på ärendena som länkas här inte syns (då dessa issues tillhör våra interna delar). Lägger därför en print här som referens till tidigare kommentarer:
![image](https://github.com/studio27se/ehub/assets/9091372/f5c46ccc-b00d-4cc5-b9f2-e18ea9596302)

**Comment by FredrikElliot** [comment]
Nu har jag plockat bort de förbättringarna ni vill vänta med, och har lagt de i egna issues istället.
#39 
#38

**Comment by FredrikElliot** [comment]
Nu är de två förbättringarna som ni gett grönt ljus också klara för test. 
@MonaAdawi @johulls @martinaskoghtham

**Comment by MonaAdawi** [comment]
@FredrikElliot jag har testat båda och dom är ok! Du kan stänga denna.
fyi @johulls @MartinaSkoghTham
