### ISSUE TITLE
Bekräftelse när man har skapat en ny störning har försvunnit på webben

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#41]
**Beskriv buggen**
Om ni tittar på vårt användartest med Tobbe (https://affarsverken.sharepoint.com/:v:/r/sites/Frbttradinformationviddriftavbrott/Delade%20dokument/General/Anv%C3%A4ndartester/Tobias_20%20mars/1.WEBB_Tester%20av%20Ehub-20240320_102308-M%C3%B6tesinspelning.mp4?csf=1&web=1&e=ARAo5U)
Finns i Teams under mappen Användartester. Välj Tobbe och Webb-filen. **Titta 3 min och 22 sek in i filmen.** Det som sker när han registrerar en störning med bekräftelse och info om störningen i grått i "Headern" dyker inte upp längre. Dock skickas sms ut. Och för varje gång man klickar på "Registrera" så kommer ett nytt SMS, men ingen bekräftelse på webben. 

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
Vi vill ha tillbaka all bekräftelse när man registrerar en störning och vi vill inte att man INTE ska kunna registrera samma störning flera ggr om inte nån förändring skett.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare Explorer

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by MonaAdawi** [comment]
@FredrikElliot vi testade detta minuten innan jag skickade in buggen här. Så alltså för ca 1h sedan.

**Comment by FredrikElliot** [comment]
Detta är nu åtgärdat! @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot  toppen @johulls har testat och bekräftar att det funkar så du kan stänga denna.
