### ISSUE TITLE
Förklaringar och flödesbeskrivning för SMS-notiser, push-notiser, mail-notiser

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#42]
**Beskriv buggen**
Hej,
Vi har testat och försöker förstå hur notiserna funkar men reder inte ut det själva!
Kan vi boka en separat tid inkl testa tillsammans.  

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Jag tänker att det här issuet mer är ett mail :) Jag stänger detta och så lägger jag ett nya gällande diskussionen vi hade imorse; Påminnelsehantering. Mottagargruppförändringen finns i #13
