### ISSUE TITLE
Rubriker för olika statustider

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#43]
**Beskriv buggen**
Förväntad avslutning ligger över Faktisk startid i appen och när du har avslutat ett ärende så hamnar tiden för det under utan rubrik

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till statusuppdatering
2. Klicka på ny status valfri
3. Välj ny tid
4. Se felet

**Förväntat beteende**
Edit av Fredrik efter möte 8/4: Justerta ordningen på tidern enligt följande:

- Förväntad starttid
- Faktisk startid 
- Förväntad avslutning

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare chrome
![Bild 1](https://github.com/studio27se/ehub/assets/160236603/6193042a-1a59-48d4-8d4b-d214af14ad75)
![Bild2](https://github.com/studio27se/ehub/assets/160236603/bb5d19af-15ae-4d75-955b-d99be0e96fd0)

**Comment by FredrikElliot** [comment]
Efter möte med Affärsverken:
Justera, och fastställ ordningen på datum-tiderna i vyn för specifik driftstörning i mobilappen enligt följande, från överst:

- Förväntad starttid
- Faktisk startid
- Förväntad avslutning

**Comment by johulls** [comment]
Ja det stämmer @FredrikElliot justera endast ordningen enligt ovan det blir bra.

**Comment by FredrikElliot** [comment]
Detta har nu justerats i och med version 1.2.5. @johulls @monaadawi

**Comment by johulls** [comment]
Hej @FredrikElliot 
När jag skapar en planerad driftstörning så får jag upp Förväntad starttid, förväntad avslutning efter som jag har fyllt i datum och tid för det. När jag sedan uppdaterar ärendet med att arbetet är påbörjat och fyller i datum och tid för det så kommer inte "Faktisk startid" fram. Det är fortfarande bara Förväntat tiden som vissas.

**Comment by FredrikElliot** [comment]
@johulls 
Var fyller du tid för att du påbörjat arbetet menar du? Detta syns i nuläget bara om man manuellt går in under klockan i appen och justerar den faktiska starttiden. Vi inväntar dock beslut från er angående att prompta användarna att fylla i faktisk starttid vid första statusförändringen. Se #38 (som i nuläget dock bara nämner planerade störningar, men som vi lika gärna skulle kunna applicera för båda typerna).

**Comment by FredrikElliot** [comment]
Efter samtal med johulls kommer vi fram till att den här är korrekt och kan stängas.
