### ISSUE TITLE
Antal påverkade kunder uppdateras inte på befintliga störningar

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#44]
**Beskriv buggen**
I appen, om man vill lägga till objekt i en pågående störning. Så uppdateras inte räknaren för antalet påverkade kunde. Se bild. 
![bugg1](https://github.com/studio27se/ehub/assets/164028902/76c89475-941d-46b7-b9d9-8dfe9818c635)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
Iphone13 IOS 17.3.1

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Detta är åtgärdat sedan användartesterna. Skulle ni kunna testa igen? Senaste version är 1.2.3.

**Comment by MonaAdawi** [comment]
@FredrikElliot jag testade igår men fick också veta att jag inte har senaste app-versionen. Det funkade inte när jag testade. Så därför måste @johulls testa denna och meddela.

**Comment by johulls** [comment]
Hej!

Denna  fungerar både i app och på webben, den kan stängas.

//Johan

**Comment by johulls** [comment]
Det fungerar i båda miljöerna och kan stängas.

@FredrikElliot @MonaAdawi
