### ISSUE TITLE
Sista statusen markeras inte som stängd

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#45]
**Beskriv buggen**
När en status passerar sista statusen (i appen) så markeras den inte som stängd när man kollar på den i webben.

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Detta är åtgärdat sedan användartesterna. Skulle ni kunna testa igen? Senaste version är 1.2.3.

**Comment by MonaAdawi** [comment]
@FredrikElliot det blir @johulls som får testa och bekräfta.

**Comment by johulls** [comment]
Hej @FredrikElliot!
Detta fungerar fortfarande inte, jag behöver gå in i webben och välja samma status engång till då stängs det även där och flyttas till filtreringen för "Stängda störningar".
Kan det vara så att under statusar så ligger status för planerade arbeten med ett högre "Flöde" värde än sista statusen för akut ärende? 
Jag har stängt ärende 204 i appen och den ligger kvar i webben under filtrering "Pågående/Planerade" men i status fältet står det "Felet är nu avhjälpt leverans återställd".

@MonaAdawi 

//Johan

**Comment by FredrikElliot** [comment]
Stänger detta issuet då vi har dublett i #32
