### ISSUE TITLE
Tilldela användare - visa per AO

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#49]
**Beskriv den lösning du önskar**
Listan över ”Tilldela användare” ska endast visa personer inom valt/resp område.

Addera taggarna: Estimat + Prio Hög + Innan nästa AO

![förbättring4](https://github.com/studio27se/ehub/assets/164028902/ff095128-3423-4eca-931a-da58ff5b225b)

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Detta är redan så systemet är implementerat. Alla användare ni ser i listan idag (vet inte om listan på bilden stämmer, för jag vet inte när bilden är ifrån) har behörighet till den valda kategorin. Exempelvis saknar Christian behörighet till någon kategori, och är således aldrig med i listan.

Kan ni testa igen?

@MonaAdawi @johulls

**Comment by FredrikElliot** [comment]
Yes, båda dessa hade Stadsnät i sin behörighet. Jag har plockat bort detta från dem båda nu, så du kan testa @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot underbart nu ser det bättre ut när jag kollar! @johulls säkerställer behörigheter så listan visar rätt per område. När Johan bekräftat stänger vi detta ärende :)

**Comment by johulls** [comment]
Det fungerar ni kan stänga denna.

//Johan

**Comment by johulls** [comment]
Det fungerar och kan stängas.

@FredrikElliot @MonaAdawi
