### ISSUE TITLE
Låsa modul på webb

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#50]
**Beskriv den lösning du önskar**
Vill att rödmarkerad modul ska låsas så den alltid syns i vyn när man behöver scrolla. Risk att glömma "spara" när spara-knappen alltid försvinner vid scroll nedåt. 
![förbättring5](https://github.com/studio27se/ehub/assets/164028902/364c7a32-0a48-4307-9edd-2fd6b7eed2bd)

Addera taggarna: Estimat + Prio Hög + Innan lansering

Obs! Endast innan lansering om inte datum för lansering riskerar att bli försenat. 

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Make outage details header sticky

- [ ] https://github.com/studio27se/ehub-webapp/issues/255

**Comment by MonaAdawi** [comment]
@FredrikElliot ja du har rätt. kanske det inte är lika stort problem när man sitter med stor skärm på kontor, och det är väl det man gör större delen av tiden @johulls? Då behöver man inte scrolla. Baserat på vad ni kommer fram till Fredrik kanske vi klassar ner denna i prio.. Och vill även höra Johans svar.

**Comment by FredrikElliot** [comment]
Här är en liten video som visar på hur det ser ut om vi implementerar en stickighet till menyn i driftstörningarna. Koden är klar, så det är egentligen bara för oss att mergea in den om ni tycker att det är bra så. Personligen tror jag som jag skrev att det mest kommer vara besvärligt (dock inget som kommer märkas på stora skärmar där det inte ens går att scrolla (om inte historikloggen är lång)). 
https://github.com/studio27se/ehub/assets/9091372/c4cb870b-bd03-4dc7-8244-abb80d5305cf
@johulls @MonaAdawi

**Comment by johulls** [comment]
Det ser OK ut men som både @FredrikElliot och @MonaAdawi har påtalat så känns det onödigt då det fungerar utmärkt på stor skärm.

**Comment by FredrikElliot** [comment]
Ska jag tolka det som att vi scrappar den här idén?
@johulls @MonaAdawi

**Comment by MonaAdawi** [comment]
Nej nej vi scrappar inget än! :)

@FredrikElliot du skrev innan så här: "Det finns en risk att menyn måste göras om för att inte äta upp för mycket av arbetsytan när man sitter på en mindre skärm (vilket jag förutsätter att man gör om man behöver scrolla upp/ner för att se menyn)"
Är det det du menar blir besvärligt? Eller har nåt nytt besvärligt dykt upp i denna?

@johulls

**Comment by FredrikElliot** [comment]
Yes. Nej, inget mer besvärligt - Bara det att vi täcker över en del av skärmen med menyn. Jag kan lägga lite tid på att se till att en fastlåst meny är optimerad i storlek (dvs mindre). Jag ville inte göra det innan ni bestämt er för att ni vill köra på detta. Men jag tror ändå att vi löser ett problem som kanske inte är så stort..?

Helt upp till er dock!
@MonaAdawi @johulls

**Comment by FredrikElliot** [comment]
Den här kan nu testas i UAT @MonaAdawi 
Ni hittar en ny liten switch som aktiverar sticky header precis under spara knappen inne på en driftstörning.

**Comment by johulls** [comment]
@FredrikElliot @MonaAdawi  Det fungerar utmärkt för mig!

**Comment by MonaAdawi** [comment]
@FredrikElliot mig med! Klarmarkera :)

**Comment by MonaAdawi** [comment]
@FredrikElliot det jag skriver i min kommentar ovan - är det förväntat när man låser modulen?

**Comment by FredrikElliot** [comment]
Nej, men jag har fixat det nu! Det var menyn som dolde underalternativen.
@MonaAdawi
