### ISSUE TITLE
Påverkade kunder följer med till nästa vy på webben

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#52]
**Beskriv den lösning du önskar**
Vi vill att antal påverkade kunder följa med till nästa flik/steg där man ska ange antal påverkade kunder. 
Tagga med: Estimat + Prio Låg + efter lansering
![förbättring7](https://github.com/studio27se/ehub/assets/164028902/651e9bec-627c-4569-acdd-991db980d83c)

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Den här kräver ca 2-3 tim

**Comment by FredrikElliot** [comment]
Detta är nu redo för test @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Nåt är fel med UAT jag kan inte logga in
![image](https://github.com/user-attachments/assets/3b963dde-6583-4901-913e-a8c144529d96)

**Comment by FredrikElliot** [comment]
@MonaAdawi Redo för test

**Comment by MonaAdawi** [comment]
@FredrikElliot Ok på denna.
