### ISSUE TITLE
Val av sista status ska fråga om faktisk sluttid

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#53]
**Beskriv buggen**
När man väljer den sista statusen i en driftstörning ska man få frågan om man vill sätta en faktisk sluttid. I nuläget fråga appen om man vill sätta en förväntad sluttid. Detta måste justeras. Dessutom ska användaren kastas tillbaka till driftstörningslistan. Det sker inte heller i nuläget.

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
När jag väljer sista statusen ska appen fråga mig om jag vill sätta en faktisk sluttid (med "nu" som förifyllt). När jag sparar ska jag flyttas till listan med driftstörningar och inte längre se störningen som nyss stängts.

**Skärmbilder**
![image](https://github.com/studio27se/ehub/assets/9091372/bcfec796-98c0-4473-8582-4c4582b15448)

**Smartphone (vänligen fyll i följande information):**
 version 1.2.3

** Utvecklingsisseus **

- [ ] studio27se/ehub-app-ionic#435
- [ ] studio27se/ehub-app-ionic#436

**Comment by MonaAdawi** [comment]
@FredrikElliot den frågar inte om faktisk sluttid, den frågar om man vill uppdatera förväntad sluttid? Datum o tid är ifyllt, men rubriceringen stämmer inte..
@johulls

**Comment by FredrikElliot** [comment]
Nej, utan det är det som ändrats i senare diskussioner (som finns dokumenterat i #32) som jag skrev :) 
Så kravet var att när man generellt byter status ska det frågas efter förväntad sluttid. Men när man väljer sista statusen får man istället frågan om man verkligen vill avsluta driftstörningen. Ingen fråga om tids ges, utan detta sätts istället automatiskt av eHUB när driftstörningen avslutas.

@MonaAdawi

**Comment by MonaAdawi** [comment]
Jag trodde jag valde sista status i 216, men kolla på min film där jag försöker välja sista statusen men det går inte??
Filmen är för tung för att lägga här. Se separat mail ist. @FredrikElliot @johulls

**Comment by FredrikElliot** [comment]
Statusen du väljer i filmen är dock inte den sista statusen i ert flöde i nuläget. Det är den som heter Underhållsarbete avslutat. Jag kan gå igenom ert flöde så att det blir rätt och så kan vi prata om hur det sätts upp, men for now - prova med den.
@MonaAdawi

**Comment by FredrikElliot** [comment]
Nu är det löst det där med statusarna, vilka som syns när/var och att den sista avslutar korrekt.
Observera ny version 1.2.7

**Comment by MonaAdawi** [comment]
@johulls och @martinaskogtham testa och bekräfta att denna funkar korrekt, tack. Och för säkerhets skull kan ni snälla skriva här vilka statusar som avslutar ärenden. Tack :)

**Comment by johulls** [comment]
Hej @FredrikElliot 

Det fungerar både på planerat och akut och både i app och web.
Status som avslutar planerad störning är "Underhållsarbete avslutat" och för akut är det "Felet är nu avhjälpt leverans återställd"

@MonaAdawi
