### ISSUE TITLE
Stängda ärenden i app

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#58]
Hej @FredrikElliot 

Jag skulle vilja att störningar automatiskt försvinner från appen när man markerat sista statusen både på planerade och akuta störningar.
Vill man i framtiden titta i den eller ändra något så får man göra det via webben. Är det något som skulle gå att göra, om inte skulle man kunna få till en filter funktion som andra handsval, så man kan filtrera bort stängda störningar.

**Comment by FredrikElliot** [comment]
Detta är så det är tänkt att fungera (och finns redan färdigt), så absolut! Det kommer en bugg-fix-uppdatering i eftermiddag där detta kommer ingå. Uppdaterar detta issues när det finns på plats!
@johulls

**Comment by FredrikElliot** [comment]
Detta är nu redo för test i v.1.2.5 
@johulls @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot jag ser inte att en störning försvinner från listan när jag valt sista status.. (Jag är i 1.2.5)
@johulls

**Comment by FredrikElliot** [comment]
Ditt problem med att se "stängda" störningar i listan hörde ihop med problemet kring statusarna och att driftstörningarna helt enkelt inte var stängda och därför syntes. Testa igen nu när statusarna är fixade. Observera ny version 1.2.7
@MonaAdawi  @johulls

**Comment by johulls** [comment]
@FredrikElliot jag kör ver 1.2.7.
Jag har provat att skapa en ny planerad och en ny akut störning och avsluta dom i appen men båda ligger kvar i listan i appen.
På akut störning valde jag kategorin " Felet är nu avhjälpt leverans återställd och på planerad valde jag Underhållsarbete avslutat.

//Johan
