### ISSUE TITLE
Skärgårdstrafiken PÅverkade objekt

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#60]
**Beskriv buggen**
När jag skapar en ny störning för Skärgådstrafiken så får jag inte möjlighet att välja status och orsak med hänvisning till att jag inte har valt påverkade objekt. I bifogat dokument kan man se att jag har valt Astrid som på verkat objekt. trots detta så tycker inte systemet det när jag kommer till Status och Orsak. 

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare chrome

Jag misstänker att jag har missat något när jag har lagt upp Skärgårdstrafiken kan ni se vad som är fel, bug eller det jag har lagt upp.

- [x] https://github.com/studio27se/ehub-webapp/issues/266

**Comment by MonaAdawi** [comment]
@FredrikElliot när tror ni att denna kommer bli löst? Vi har inte satt nån prio men ni får gärna lösa så snart ni kan.. Tack.

@johulls

**Comment by FredrikElliot** [comment]
Vi har faktiskt inte undersökt den så mycket än, för att kunna prioritera lite hårdare kring det som gäller specifikt Stadsnät. Jag återkommer!
@MonaAdawi @johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot Självklart och ni har prioriterat helt rätt där! Säg till mig om denna blir svår att hinna med samtidigt som vi INTE vill riskera satt deadline för lansering. Vi kommer inte vidare med Skärgårdstrafiken utan denna men det är egentligen inget krav heller - bara vi som vill hitta ev anpassningar som ev behöver göras för Skärgårdstrafiken i ehub, så tidigt som möjligt om det går :) 
@johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot ville bara kolla lite status på denna och hur ni ligger till att hinna fixa denna? 

Så fort denna funkar @johulls försöker vi färdigställa Skärgårdstrafiken i ehub webb.

**Comment by FredrikElliot** [comment]
@MonaAdawi Svårt att säga! Vi jobbar med BBE-integrationen och har inte utvärderat denna alls än. Om den inte är kritisk till release skulle jag ställa in mig på att den inte kommer vara löst innan användarutbildningarna..

**Comment by MonaAdawi** [comment]
Tack för återkoppling då vet jag @FredrikElliot

**Comment by FredrikElliot** [comment]
Åtgärdat och redo för test! @johulls

**Comment by FredrikElliot** [comment]
Problemet här var att ni hade glömt att välja vilken orsak som var standardorsak för Skärgårdstrafiken.
![image](https://github.com/studio27se/ehub/assets/9091372/88104e1b-1fbb-4ed8-aedd-694a12b0e75d)

Jag har nu valt väder som standard för skärgårdstrafiken. Gå gärna in och ändra det om det inte stämmer.
Vi måste kanske kika på att kunna indikera färdigställandestatus för nya kategorier någonstans i systemet, men det får nog bli senare.
@MonaAdawi @johulls

**Comment by FredrikElliot** [comment]
Jag har verifierat för Skärgårdstrafiken i AB själv, så stänger issuet :)
