### ISSUE TITLE
Editerar Objektinformation

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#61]
**Beskriv buggen**
Jag har ändrat objektinformation under gruppnamn för underobjekt på Nättraby och Rödeby. 
Efter jag gjort det och sparat så försvinner dom för mig i objektträdet nu ligger endast Jämjö kvar

Se filen 
[Felanmnälan Stadsnät.docx](https://github.com/studio27se/ehub/files/14946431/Felanmnalan.Stadsnat.docx)

**Comment by FredrikElliot** [comment]
- [ ] https://github.com/studio27se/ehub-webapp/issues/259

**Comment by FredrikElliot** [comment]
Jag har försökt att återskapa problemet (som jag förstår finns där någonstans, eftersom jag såg i datat att det blivit fel när du redigerat), men lyckas inte. Det finns inte så mycket mer jag kan göra i nuläget, mer än säga att om det händer igen ta direkt en screenshot av objektet du redigerat om trädet ser konstigt ut, och notera tiden för resigeringen. 

Jag stänger issuet, men om det dyker upp igen så bara öppna ett nytt!
