### ISSUE TITLE
Historiken uppdateras inte med ny tilldelad

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#64]
~
**Beskriv buggen**
Jag har en störning som saknar bock i visa på webb. Jag försöker bocka i den men det fastnar inte. Och jag har tidigare varit tilldelad på denna, det syns i historiken. Men jag har bytt till Johan. Dock syns inte det i historiken. Se film som jag mailar separat. 
@johulls
~

**Beskriv buggen**
Om det enda som uppdateras i en driftstörning är tilldelningen av ärendet skapas ingen historik

**Comment by FredrikElliot** [comment]
Problemet med att spara är löst! Jag gör om det här issuet till att endast handla om att historik inte skapas om det enda som uppdateras är tilldeningen.
@MonaAdawi

**Comment by FredrikElliot** [comment]
Nu är även historik-problemet åtgärdat!
@MonaAdawi

**Comment by MonaAdawi** [comment]
Tack  @FredrikElliot jag meddelar när ni kan stänga när jag testat igen.

**Comment by MonaAdawi** [comment]
@FredrikElliot denna funkar nu - jag har testat själv. Du kan stängda denna.
