### ISSUE TITLE
Lägg till actualEnd = null i web-enpoints filtrering

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#65]
Från Christian:
Hej, vi hittade en sak när vi använder ?actualEnd=yyyy-mm-ddThh:mm:ss som filterparameter. Tanken är ju att endast hämta hem de senaste driftstörningarna. Ex vi sätter datumet till 4 månader bakåt i tiden. Problemet vi upptäckt är att om en driftstörning inte har något actualEnd = null så följer de inte med ut i listan. Så kan man justera filtret att ta med de som har actualEnd = null?

Add actualEnd = null in webintegration data endpoint
- [x] studio27se/ehub-backend-api#219

**Comment by FredrikElliot** [comment]
Nu är det ändrat så att även actualEnd = null tas med vid filtreringen. Testa gärna och återkom om det skulle vara några frågor! @christian-levin

**Comment by MonaAdawi** [comment]
Påminnelse till dig @christian-levin att testa

**Comment by christian-levin** [comment]
@MonaAdawi Jag har testat och det fungerar. Hur stänger jag?

**Comment by FredrikElliot** [comment]
Jag stänger! :)

@MonaAdawi @christian-levin
