### ISSUE TITLE
Nya störningar kommuniceras inte ut till kanalerna

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#68]
**Beskriv buggen**
Ehub webb registrerar nya störningar men info går INTE ut i sms eller till hemsidan. Får heller ingen grön bekräftelse i ehub webb som man brukar få.
Gäller dessa 3:
![image](https://github.com/studio27se/ehub/assets/164028902/e807d555-058c-42bc-848c-04414b0b47c9)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Glömde att tagga dig, @MonaAdawi. Men den här är redo för test!

**Comment by MonaAdawi** [comment]
@FredrikElliot du kan stänga denna.
