### ISSUE TITLE
Driftstörning skärgårdstrafiken 

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#69]
**Beskriv buggen**
Jag försöker skapa en driftstörning för skärgårdstrafiken i webben jag kan lägga in störningsdetaljer, påverkade objekt och gföra mina val för kritikalitet men när jag skall välja Status och Orsak så är den sidan helt tom på val mitt i rutan står det att jag måste välja påverkade objekt innan status och orsak kan väljas. 

Jag har provat med olika objekt men inget fungerar och i detta fall så har jag valt Annaskär.

[Skätgårdstrafiken.docx](https://github.com/studio27se/ehub/files/15063661/Skatgardstrafiken.docx)

**Comment by johulls** [comment]
@FredrikElliot såg att jag redan lagt in en bugg på detta :)

**Comment by FredrikElliot** [comment]
Hej! Det här har du redan rapporterat i #60 :) Jag stänger detta så vi inte har dubletter!
@johulls
