### ISSUE TITLE
Kan inte spara "dagboksanteckning"

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#70]
**Beskriv buggen**
Jag skapade en störning. Sparade. Därefter gick jag in i störningen igen och vill addera en egen anteckning. Men fick då felmeddelande. 
Se bild. 
![image](https://github.com/studio27se/ehub/assets/164028902/736735ce-cb7f-4b79-8b56-236e75ef593e)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Det här åtgärdades igår, men glömde skriva!
@MonaAdawi

**Comment by MonaAdawi** [comment]
Tack vi har testat, det funkar så du kan stänga @FredrikElliot
