### ISSUE TITLE
Går inte att ta bort kritikalitetsfråga

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#71]
Hej @FredrikElliot 
Jag jobbar med Skärgårdstrafikens kritikalitetsfrågor och skall ta bort fråga 2 "Berörda linjer".

Detta gäller i webben chrom som läsare

//Johan

**Comment by johulls** [comment]
@FredrikElliot såg nu när jag hade jobbat med lite annat för skärgård och gick tillbaka att frågan var bort. Har du redan tagit bort den eller var det så att den inte riktigt uppdaterade sidan trots att jag laddade om sidan

**Comment by FredrikElliot** [comment]
@johulls 
Jag brukar ju vara blixtsnabb, men i det här fallet hann jag inte reagera. Så då var det nog som du skrev att det kanske inte uppdaterades ordentligt. Jag håller kvar issuet här så att jag kan göra lite dubbelkontroller innan vi skriver av "händelsen".

**Comment by FredrikElliot** [comment]
- [ ] https://github.com/studio27se/ehub-webapp/issues/267

**Comment by FredrikElliot** [comment]
Detta är nu åtgärdat! Som du trodde var det "bara" att UI inte uppdaterades ordentligt när man tog bort en fråga.

**Comment by johulls** [comment]
@FredrikElliot det fungerar och ni kan stänga detta ärende.

**Comment by FredrikElliot** [comment]
@johulls Det här ärendet handlar om kritkalitetsfrågor. Jag kopierar in ditt svar i det andra ärendet och stänger detta
