### ISSUE TITLE
Filtrering funkar inte 

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#74]
**Beskriv buggen**
Filtreringen verkar inte funka under Modulinställningar/Orsak. 
![image](https://github.com/studio27se/ehub/assets/164028902/a6a3b53b-955e-4440-8c08-a5c1d17048c7)

- [ ] [Cause filtering on category doesn't trigger re-fetch of data in outage module settings](https://github.com/studio27se/ehub-webapp/issues/282)

**Comment by FredrikElliot** [comment]
Detta är nu åtgärdat och redo för test @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot funkar nu. Du kan stänga. Tack!
