### ISSUE TITLE
Arkiverade orsaker visas i appen

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#75]
Orsaker som arkiverats visas i appen som valbara alternativ.

- [x] https://github.com/studio27se/ehub-backend-api/issues/227

**Comment by FredrikElliot** [comment]
Detta är nu åtgärdat och redo för test. @monaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot nu stämmer det, du kan stänga. Tack!
