### ISSUE TITLE
Ta bort "Berörda enheter" i alla notiser

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#76]
**Beskriv den lösning du önskar**
På uppdrag av @johulls skickar jag in önskemål att ta bort infon "berörda enheter" i alla notiser. Se exempel från mail-notis:
![image](https://github.com/studio27se/ehub/assets/164028902/32a903a0-159e-4d0a-a9a3-c44a1c4215c0)

Tagga med "efter lansering" om den tar tid att fixa. 

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Jag tänker att eftersom en av era rapporterade buggar är att man inte får notis när man sänker antalet berörda enheter är det bättre att vi lägger tiden på att implementera den här förändringen, istället för att försöka rätta till något som vi plockar bort efter lansering.
Förtydligande då (Okeja, om det stämmer): Förändring av BARA berörda enheter ska registreras och visas med en historiklogg, men inga uppdateringar ska skickas ut till användarna eller hemsidan.
@MonaAdawi @johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot okej enligt mig! Men @johulls får säga vad han tycker också.

**Comment by FredrikElliot** [comment]
### Kravbeskrivning
När en driftstörning skapas eller förändras ska det inte synas i notiser som skickas ut hur många enheter driftstörningen berör (som det gör idag). Dock ska en historiklogg skapas även om endast antalet enheter förändras.

### Kopplade utvecklingsissues

- [ ] Remove "Berörda enheter" from notification content

**Comment by MonaAdawi** [comment]
@FredrikElliot yes!

**Comment by FredrikElliot** [comment]
Det här är nu redo att testas i UAT @MonaAdawi

**Comment by FredrikElliot** [comment]
Nu ska du få sms också! :) @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Se bugg-issue #109

**Comment by MonaAdawi** [comment]
@FredrikElliot ok att stänga denna.
