### ISSUE TITLE
Testbuggar

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#77]
Följande tester är alla gjorda på [driftstörning 316](https://ehub.se/v2/outages/outage/316)

Gällande mailnotiser:
~~1 Ingen notis vid sänkning av antal berörda enheter~~ Avskrivs i och med #76 
~~2 Ny påminnelse innehåller inte antal berörda enheter~~ Avskrivs i och med #76 
3 Uppdatering från hög kritikalitet till medel gav 2 sms och 2 mail. Det ena med kort orsakstext, och det andra med lång text.

**Comment by FredrikElliot** [comment]
TEST: Change from high to low criticality: Supposed to only send single email/sms
- [ ] https://github.com/studio27se/ehub-backend-api/issues/236

**Comment by FredrikElliot** [comment]
Angående dubbla utskick:
Just nu kan vi inte se att det går iväg dubbla om vi testar samma scenario, med samma ärende igen. Allt ser normalt ut. Dock har vi begränsade möjligheter att se större loggar då vi använder ett inbyggt email-system. Det vi kan göra för att i alla fall få en bättre loggning över vad som händer är att implementera en egen email-lösning. 

Det kommer vi inte kunna ta oss an förrän efter lansering dock. Förhoppningsvis var tillfället bara en hickup, och skulle det hända igen kanske det går att leva med till efter lanseringen? Vi har ett non-functional requirement hos oss att göra en refactor på mailskick, så vi behöver inte ha kvar ärendet här. Jag föreslår att vi stänger detta. Skulle det hända igen kan ni såklart öppna ett nytt issue!

@monaAdawi

**Comment by MonaAdawi** [comment]
Låter bra @FredrikElliot

**Comment by MonaAdawi** [comment]
@FredrikElliot måste bara dubbelkolla om Nr 3 i ärendet är löst också?

**Comment by FredrikElliot** [comment]
Det är alltså nr 3 i denna som min kommentar gällde. Så, mnja. Löst, nej. Men vi har provat att repetera scenariot och kan inte återskapa felet eller se att något blir fel.. @MonaAdawi

**Comment by MonaAdawi** [comment]
Men herregud va snurrig jag är nu! Miss av mig och jag har ju redan svarat - tack och stängd! @FredrikElliot
