### ISSUE TITLE
Får ingen notis när jag uppdaterar sluttid på driftstörning

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#78]
**Beskriv buggen**
jag har skapat en akut driftsstörning #318 i ehub app och testat att ändra information i den och får notiser för ändringarna. Men när jag testar att uppdatera med ny sluttid (via appen) så uteblir notis. Är det förväntat? Sista händelsen i historiken skickas alltså ej ut som notis. Är det rätt?
![image](https://github.com/studio27se/ehub/assets/164028902/c5e2731f-4de6-4425-ac3a-f08fe5527658)

TILLÄGG: 
Jag testade att ändra sluttid via ehub webb istället och då skickas notis ut! Jag har sett att ni adderat * på den ändring som skett sedan sist. Det läggs ingen * på sluttiden på denna ändringen när jag ändrade sluttid via webben. det ligger istället på "orsak"
![image](https://github.com/studio27se/ehub/assets/164028902/6e56aec4-f8cd-4bc8-bb30-492d84eb95c7)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Det här är nu redo för test!
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot notiser kommer fram på denna nu.
