### ISSUE TITLE
Ändar knapptext för att nollställa frågesvar i mobilapp

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#8]
För att hålla termonologin konsekvent behöver vi uppdatera texten för knappen som ger användarna möjlighet att svara på kritikalitetsfrågorna för en driftstörning igen, i appen.
Idag står det "Uppdatera". Det ska ändras "Nollställ"

- [x] studio27se/ehub-app-ionic#411

**Comment by Markus-js** [comment]
Bugg löst
