### ISSUE TITLE
Jag har får inga app-notiser?

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#80]
**Beskriv buggen**
jag har Iphone 13 ios 17.4.1 just nu, men har aldrig fått några app-notiser från Ehub. Ser ut så här i mina inställningar. Vad behöver jag göra?
![image](https://github.com/studio27se/ehub/assets/164028902/d8a17179-e1a1-497b-a7e3-a41b3f539101)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Även om man trycker nej första gången ska appen hela tiden kontrollera om man eventuellt har aktiverat notiser för appen ifrån inställningarna och då registrera enheten. Men vi kör några tester för om det skulle vara något i det från vår sidan. Jag återkommer!
@MonaAdawi

**Comment by FredrikElliot** [comment]
Vi kan inte hitta något problem eller fel just nu. Skulle du kunna prova att ta bort appen och installera den igen? Jag rensar dina registreringar av notisenheter undertiden. @MonaAdawi
