### ISSUE TITLE
"Ref. " framför nummer på driftstörning i notiserna (app, sms, mail)

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#81]
**Beskriv den lösning du önskar**
Vill vi addera "Ref. " framför siffran på driftstörningar i notiserna (EJ ut på hemsidan)? Kan vara svårt o veta vad 315 innan Rödebyvägen betyder..
![image](https://github.com/studio27se/ehub/assets/164028902/cb9c0a9d-1e8e-4342-a962-a3b96ad8b92d)

För beslut med @johulls
Tagga med efter lansering

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
### Kravbeskrivning
Prefixa en driftstörnings id-nummer med `Ref. ` i textinnehållet i både mail och sms vid uppdatering/registering av en driftstörning.

### Kopplade utvecklingsissues

- [ ] Prefix outage id with "Ref. " in notification text/email

**Comment by MonaAdawi** [comment]
@FredrikElliot yes!

**Comment by MonaAdawi** [comment]
Jag får bara mailnotiser och där ser jag Ref. Men jag godkänner inte denna förrän jag sett sms också och dom får jag inte för tillfället enligt tidigare diskussion @FredrikElliot 
@johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot Tack Ref finns med i sms också så nu är denna ok :)
