### ISSUE TITLE
Mina svar på kritikalitetsfrågorna i en bef. störning nollställs

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#83]
**Beskriv buggen**
Jag skapade en ny akut störning #325. Sparade. Sen gick jag in och uppdaterade sluttid och sen även påverkade objekt. När jag tryckte spara efter att jag ändrade påverkade objekt så hade formulärets "nollställts"
![image](https://github.com/studio27se/ehub/assets/164028902/877e9178-f3c0-4cca-b3f3-f3a031c79afa)

OBS! Jag testade att ändra fler saker och det verkar vara så att formuläret nollställs varje gång jag ändrar i **påverkade objekt** - inte annars (vad jag upptäckt)

**Comment by FredrikElliot** [comment]
Yes! Enligt beslut från er ville ni att frågorna skulle svaras på igen om man ändrar berörda enheter. Jag har för mig att argumentet var: Om läget har förändrats, ska frågornas svar omvärderas.
@MonaAdawi

**Comment by FredrikElliot** [comment]
DOCK! I webappen görs detts i ett och samma flöde, men i appen finns det i nuläget inget som tvingar dig att svara på frågorna igen om du uppdaterar enheterna. Så det är en inskonsekvens i flödet mellan webapp och mobilapp där. Kanske värt att fånga upp efter lansering.

**Comment by FredrikElliot** [comment]
Helt okej! Skriv ner hur ni vill att systemet ska bete sig i den här situationen så vi har ert krav kring det hela 👍 
@MonaAdawi @johulls

**Comment by johulls** [comment]
@FredrikElliot @MonaAdawi Det räcker definitivt till efter lansering. Vi sätter oss ner och tittar och återkommer med hur vi vill att det skall bete sig.

**Comment by MonaAdawi** [comment]
@johulls för tydlighetens skull, du har den här bollen :)

**Comment by FredrikElliot** [comment]
Clearat av Johan under möte 2024-06-14
