### ISSUE TITLE
Förändring i påverkade objekt ska loggas i historik

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#84]
**Beskriv den lösning du önskar**
Jag lägger in denna finding för oss att diskutera tillsammans @johulls @FredrikElliot 
När jag skapar störningar och uppdaterar störningar och ändrar **påverkade objekt.** Så loggas/sparas inte det i ngn historiklogg. Jag själv hade velat ha historik på alla ändringar som gjordes om det gällde mitt område.

**Comment by FredrikElliot** [comment]
Nu! 👍 @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Se bugg-issue #109

**Comment by MonaAdawi** [comment]
@FredrikElliot jag har testat och denna är ok och syns som det ska i historiken nu!
