### ISSUE TITLE
Sluttid skiljer i notis och webb

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#85]
**Beskriv buggen**
Jag gjorde en ändring på sluttid på en störning via appen. Klockslag som skickas ut med notis skiljer sig från vad som visas på störningen. (tidzon som spökar igen?):
![image](https://github.com/studio27se/ehub/assets/164028902/5d4b7511-94a2-4015-8f78-6a7c7b2e61eb)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Time differences in displayed text; History content, email sendout and data

- [ ] https://github.com/studio27se/ehub-backend-api/issues/230

**Comment by MonaAdawi** [comment]
@FredrikElliot fortfarande fel och en diff på 2h.

**Comment by FredrikElliot** [comment]
Vet inte varför det här gick igenom vår review. Men det är åtgärdat nu!
@MonaAdawi Du fick precis ett sms som bekräftar att tiden stämmer nu :)
