### ISSUE TITLE
Radbyte i mailnotiser

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#87]
**Beskriv den lösning du önskar**
Vissa mailnotiser är inte så "lättlästa" när dom inte har radbyte per information. En info per ny rad. Den verkar strunta i radbyte vid uppdateringar?? Detta vill vi alltså se över:
![image](https://github.com/studio27se/ehub/assets/164028902/587ea9dc-7ca1-4a83-a035-27e8bdf4965c)

Efter lansering.

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Det här har mer att göra mer hur epost-klienten tolkar innehållet i mailet. Men jag har justerat så att innehållet skickas med i fler format, så att klienten ska kunna tolka det både som html eller oformaterat innehåll och ändå få det rätt. Hos mig ser det rätt ut, men det har gjort hela tiden.. Skulle du kunna kolla hur det senaste mailet du fick 13.11 ser ut? @MonaAdawi

**Comment by MonaAdawi** [comment]
Okej. Ser inte bra ut tyvärr @FredrikElliot 
![image](https://github.com/studio27se/ehub/assets/164028902/dfec4f3f-e7b5-460c-9f44-8fa624cee3d1)

**Comment by FredrikElliot** [comment]
Då får vi nog kolla på det här efter lanseringen. Jag använder outlook som klient, och den tolkar om det här mailet korrekt med radbrytningar. Kan du prova att kolla mailet i outlook i webben? @MonaAdawi

**Comment by FredrikElliot** [comment]
Se #89 @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot denna blev lite rörig för mig... den hänvisar runt mig. Vad gäller här? :)

**Comment by FredrikElliot** [comment]
Den här handlar om att raderna satt ihop som på första bilden du skickade. Jag tror att jag i #87 också skrev att lösningen där löste även denna.

**Comment by MonaAdawi** [comment]
@FredrikElliot right! Stäng :)
