### ISSUE TITLE
Fel statusalternativ visas om jag INTE bockar i "Planerad" störning direkt (första steget)

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#88]
**Beskriv buggen**
Om jag skapar en ny störning och tex glömmer att bocka i att den är planerad i första steget, och så fortsätter jag i flödet och fyller i alla stegen. Kommer till sista steget och ska välja Status och orsak. Där ser jag att den visar statusar för Akut störning. Då går jag tillbaka till första steget och bockar i att det är en planerad störning. Sen tillbaka till sista steget igen. Då ändras inte alternativen för status och orsak utan dom är kvar för Akuta störningar. Om jag däremot bockar i Planerad direkt, så visas rätt alternativ i listan. 
![image](https://github.com/studio27se/ehub/assets/164028902/1e9dc873-be17-4159-aae9-d2f25728884a)
![image](https://github.com/studio27se/ehub/assets/164028902/61fd947c-6d45-481b-90a3-0d6e4e8894ef)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Check "planned outage" doesn't refresh the status-box
- [ ] https://github.com/studio27se/ehub-webapp/issues/288

**Comment by FredrikElliot** [comment]
Detta har nu åtgärdats! @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot denna är ok nu du kan stänga :)
