### ISSUE TITLE
Fel texter i mailnotiser

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#89]
**Beskriv buggen**
Jag hittar inter logiken men jag får fel orsakstexter i mailnotiserna, ibland. 
Rätt
![image](https://github.com/studio27se/ehub/assets/164028902/26c44099-5556-4ad3-97db-20f4df71e5b7)
Fel
![image](https://github.com/studio27se/ehub/assets/164028902/506224cb-d667-4331-9d85-32c125e25566)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Just nu har vi inte separat hantering av vilken orsak som används i påminnelseutskick för planerade driftstörningar. Där används samma innehåll till både sms och epost, vilket är anledningen till att du har en annan orsakstext i påminnelsemailet. Vi kan kika på att justera detta efter lanseringen om det behövs? @MonaAdawi

**Comment by FredrikElliot** [comment]
Här ser det ju dessutom ut som att radbrytningen funkar?

**Comment by MonaAdawi** [comment]
@FredrikElliot okej då vet jag det. Här kommer en störning som inte är en påminnelse:
![image](https://github.com/studio27se/ehub/assets/164028902/45eede4c-fdd5-429d-a492-42194e2bb318)

**Comment by MonaAdawi** [comment]
> Här ser det ju dessutom ut som att radbrytningen funkar?

Yes det funkar ibland och ibland inte. Jag misstänker att det inte funkar lika bra när jag gör en uppdatering på en störning.

**Comment by MonaAdawi** [comment]
@FredrikElliot Nu fick jag 2 störningar på samma störning. Men det andra mailet kom 1 min senare. Står inget om påminnelse, men texterna skiljer sig:
Mail 1:
![image](https://github.com/studio27se/ehub/assets/164028902/60c3c347-85fa-4cb8-8fa0-b1cc7ef514b0)
Mail 2:
![image](https://github.com/studio27se/ehub/assets/164028902/38a89e80-9140-40d7-b896-3bbb849cc542)

**Comment by FredrikElliot** [comment]
Då har vi justerat radbrytning, områdestexter etc. Vi har också hittat en förmodad anledning till att du fått dubbla epost.
Även logotypstorleken är justerad till storleken det är tänkt, så att den läses korrekt för epost-klienter utan html-tolkning.
@MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Ska vi låta denna vara öppen tills vi åtgärdat dubbla notiser? Eller skapa en ny/egen issue. Den är inte löst enligt tester fg vecka.

**Comment by FredrikElliot** [comment]
Eftersom vi har #92 tänker jag att vi kan stänga denna! @MonaAdawi
