### ISSUE TITLE
Regelverk Titel på störningarna (i notiser och ut mot hemsidan + app och webb)

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#90]
**Beskriv den lösning du önskar**
Här kommer listan som vi ska utgå ifrån när vi ska sätta Titel på störningarna, baserat på vilka noder som är valda
[Lista placering noder.xlsx](https://github.com/studio27se/ehub/files/15435830/Lista.placering.noder.xlsx)

Obs! Klar innan lansering

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Det här implementerat, och uppdateringarna av felaktiga namn är justerade.
@MonaAdawi

**Comment by MonaAdawi** [comment]
Tack du kan stänga denna @FredrikElliot
