### ISSUE TITLE
Dubbla mail gällande planerade driftstörningar med starttid inom ett dygn från skapandetid

### ISSUE THREAD

**Issue by FredrikElliot** [studio27se/ehub#92]
387 skapades kl 11:46. Avslutades 11:50.
Bilder från 2024-05-30:
![image](https://github.com/studio27se/ehub/assets/9091372/df5dbb1d-58a5-4441-be81-b04608a67cf3)
![image](https://github.com/studio27se/ehub/assets/9091372/7c71a9a2-ca60-4bdc-891d-0bfeccd6068f)

**Comment by FredrikElliot** [comment]
@MonaAdawi (skriver det här också så vi har koll!)
Den här har blivit nedprioriterad under arbetet, men är inte bortglömd. Vi pratade internt om den så sent som i måndags morse. Vår förhoppning är att vi ska kunna få med fixen till nästa release (dvs. inte nu på torsdag 12/).

**Comment by FredrikElliot** [comment]
@MonaAdawi Har du kvar de dubbla mailen du fick? Vi har lite svårt att hitta material som vi kan använda för felsökning. Skulle du annars kunna rapportera direkt när det händer nästa gång, och vilket case det rör så att vi kan hitta var i koden det slinter?

**Comment by MonaAdawi** [comment]
@FredrikElliot jag har tyvärr inte sparat mailen som kom dubbelt, men jag ser att jag skriver ovan att det gäller störning 387 om det skulle kunna hjälpa felsökningen?

**Comment by FredrikElliot** [comment]
Tack @MonaAdawi Vi började felsöka med hjälp av detta igår.

**Comment by FredrikElliot** [comment]
Bekräftad via mail. Stänger issue!
