### ISSUE TITLE
Objekt

### ISSUE THREAD

**Issue by johulls** [studio27se/ehub#93]
**Beskriv buggen**
När man är under "Lista objekt" och klickar på ett objekt vilket som och både i Affärsverken AB och Affärsverken UAT så får man upp ett felmeddelande enligt med skick. Det hjälper inte att ladda om sidan.

[Felmeddelande.docx](https://github.com/user-attachments/files/15509062/Felmeddelande.docx)

**Comment by FredrikElliot** [comment]
Det här har nu åtgärdats med en snabbare lösning i kontakten med BECS. @johulls

**Comment by FredrikElliot** [comment]
Detta är bekräftat under mötet imorse.
