### ISSUE TITLE
Rensa gamla driftstörningar i Affärsverken AB

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#94]
**Beskriv den lösning du önskar**
Imon lördag 1 juni är vi live med Ehub Stadsnät och all info kommer visas ut mot hemsidan. Innan det sker vill jag gärna rensa Affärsverken AB från gamla (test-driftstörningar. Kan ni göra det idag fredag 31/5? Tack.
![image](https://github.com/studio27se/ehub/assets/164028902/069314f1-e4db-45b9-865a-db60e8747af1)

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Klart! @MonaAdawi
