### ISSUE TITLE
Justera design mailnotiser

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#95]
**Beskriv den lösning du önskar**
Idag får Affärsverken mailnotiserna på grå bakgrund. Det är väldigt svårläst så det måste vi justera. jag vet att det kanske ser annorlunda ut i andra mailklienter. men eftersom det är så här vi ser det så måste det justeras. Fetstilt ska även adderas på rubrikerna. Och förändringar markeras med *--* istället för fetstilt. Kanske redan finns en issue på detta men hittade inte så la in denna nu.
![image](https://github.com/studio27se/ehub/assets/164028902/1adda9d6-88cd-412f-bf96-05c1c4efafd8)

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
@MonaAdawi 
Vi har nu justerat utseendet på mailen och hittat en kompromiss som borde fungera även i era klienter. Även om den vita bakgrunden inte syns, är texten som skrivs ut i mailet kontrastsäker för digital läsning. Testa gärna vad ni tycker!

**Comment by FredrikElliot** [comment]
Nja, såhär ska det se ut.. Men det är eventuellt inte så mycket att göra åt om styling blockeras av er mailserver.. Så länge ni kan ta del av informationen på ett bra sätt!
![image](https://github.com/studio27se/ehub/assets/9091372/692d8707-2b63-4322-b4a4-c7413df03f68)

**Comment by FredrikElliot** [comment]
Bekräftat i möte med Mona
