### ISSUE TITLE
Starttid (och sluttid) driftstörning obligatoriskt fält

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#96]
**Beskriv den lösning du önskar**
Vi tror att vi kommer vilja sätta starttid som ett obligatoriskt fält. Idag är det inte. Vi diskuterar internt och ger besked efter det @johulls

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
### Kravbeskrivning
**Mobilappen**
- När man skapar en planerad driftstörning ska det inte gå att hoppa vidare utan att ange ett värde i Planerad starttid
- När man skapar en akut driftstörning ska det inte gå att hoppa vidare utan att ange ett värde i Faktisk starttid

**Webbappen**
- När man skapar en planerad driftstörning ska man få ett felmeddelande om man försöker skapa en driftstörning utan att ha angett Planerad starttid
- När man skapar en akut driftstörning ska man få ett felmeddelande om man försöker skapa en driftstörning utan att ha angett Faktisk starttid

### Kopplade utvecklingsissues

- [ ] Mobile: Make start time mandatory
- [ ] Web: Make start time mandatory
- [ ] Backend: Make star time mandatory

**Comment by FredrikElliot** [comment]
@johulls, bekräfta att vi har förstått er rätt enligt ovan kravbeskrivning. Kommentera om något use case saknas i förändringarna ni förväntar er.

**Comment by johulls** [comment]
@FredrikElliot  Det är som du har beskrivit ovan, det jag tycka när vi ändå pratar om tider är att även förväntat sluttid på planerad driftstörning skall vara obligatorisk vad tycker du @MonaAdawi

**Comment by FredrikElliot** [comment]
Ni kan väl prata ihop er och sedan kommentera era tillägg här så skriver jag om beskrivningen.  Alternativt bestämmer ni er för att detta är vad ni vill göra nu, och sparar diskussionen till ett annan issue. Vi kommer inte kunna starta förrän vi har en godkänd kravbeskrivning från er. Återkom!
@johulls @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot jag och @johulls har pratat och är överens om att även planerad störning måste ha obligatorisk förväntad sluttid. Så vi kör på det!

**Comment by FredrikElliot** [comment]
### Kravbeskrivning
**Mobilappen**
- När man skapar en planerad driftstörning ska det inte gå att hoppa vidare utan att ange ett värde i Planerad starttid och Planerad sluttid
- När man skapar en akut driftstörning ska det inte gå att hoppa vidare utan att ange ett värde i Faktisk starttid

**Webbappen**
- När man skapar en planerad driftstörning ska man få ett felmeddelande om man försöker skapa en driftstörning utan att ha angett Planerad starttid och Planerad sluttid
- När man skapar en akut driftstörning ska man få ett felmeddelande om man försöker skapa en driftstörning utan att ha angett Faktisk starttid

### Kopplade utvecklingsissues

- [ ] Mobile: Make start time (and planned end time) mandatory
- [ ] Web: Make start time (and planned end time) mandatory
- [ ] Backend: Make star time (and planned end time) mandatory

**Comment by FredrikElliot** [comment]
Har uppdaterad kravbeskrivningen. Sätt en tumme upp så kan vi köra! @MonaAdawi @johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot go!

**Comment by FredrikElliot** [comment]
Den här nu redo för test! @MonaAdawi 
Vi inväntar just nu mobilversion 1.4.0 i Testflight (du får en pling i telefonen när den är redo för test). Det är dock redan släppt i webbappen.

**Comment by MonaAdawi** [comment]
@FredrikElliot jag testade denna nyss och skapade en ny störning o lämnade medvetet tomt på sluttid. Se bilder. 
Får ett felaktigt felmeddelande:
![image](https://github.com/studio27se/ehub/assets/164028902/0bf68758-2fc2-4063-aafe-dff66edaafc4)

**Comment by MonaAdawi** [comment]
@FredrikElliot denna är ok att stänga.
