### ISSUE TITLE
Synpunkter Affv ledningsgrupp

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#97]
**Beskriv den lösning du önskar**
**Caroline:** 
Ett litet önskemål skulle kunna vara att kritikaliteten skulle synas högst upp i smset tex ”Ny driftstörning – Hög” så att direkt får en uppfattning om det på skärmen. 
**Therese:** 
jättebra att förändringar är markerade med asterisker, det förtydligar vad vi ska titta efter.
Jag skulle önska att se ungefär hur många kunder avbrottet drabbar.

För diskussion och prioritering @johulls
@FredrikElliot Det kanske blir utveckling på detta eller inte :)

**Förslag eller förfrågan**
Är ditt ärende ett förslag för framtida förbättre, eller vill ni skapa en förfrågan om ändring? Vid förfrågan svarar vi alltid med ett estimat, när alla detaljer retts ut, innan arbetet påbörjas.

**Ytterligare sammanhang**
Lägg till annan kontext eller skärmbilder om funktionen här.

**Comment by FredrikElliot** [comment]
Beslut från Affv: Vi stänger utan åtgjärd.
