### ISSUE TITLE
Ser inte driftstörningar i UAT Skärgårdstrafiken på hemsidan Stagemiljö

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#98]
**Beskriv buggen**
Hej, Störningar på Skärgårdstrafiken i UAT syns inte på hemsidan Stage. Se pågående störningar som borde synas i bilden. Vi kan dock se att dom skickas till hemsidan produktionsmiljön. Hemsidan Stage verkar inte ha rättigheter att se störningarna i UAT? Kan ni kolla på det så snart ni kan så vi kan se störningarna på Stage också. Tack. 

![image](https://github.com/studio27se/ehub/assets/164028902/8628d603-8871-4c28-ad5c-cac66f1b3871)

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
stage ska gå mot den nya uat-länken jag skickade till dig (https://api.uat.ehub.se). Där finns inte produktion, utan bara UAT-data så det är en omöjlighet att produktionsdata syns. Nu råkar det vara så att vi har kopierat mycket av datat från prod över till uat, för att ni inte skulle behöva börja om från noll. Men om du provar att skapa en ny driftstörning i uat-miljön ska den visas på hemsidan, förutsatt att url:en är uppdaterad.
@MonaAdawi 
Stänger detta issuet, eftersom det blir lite mer ett service-ärendet än en utveckling. Kör på mail om det fortsatt inte funkar!
