### ISSUE TITLE
Vi kan inte avsluta/stänga störningar på Skärgårdstrafiken UAT

### ISSUE THREAD

**Issue by MonaAdawi** [studio27se/ehub#99]
**Beskriv buggen**
Vi kan inte avsluta/stänga störningar på Skärgårdstrafiken UAT. I flödesvärdet på Skärgård höjde vi värdet på sista statusen till nr 15 och då har den det högsta värdet av samtliga statusar (Inkl för Stadsnät) och då funkade det att stänga, så vi tror inte att flödesvärdena är unika per kategori. 

**För att reproducera**
Steg för att återskapa beteendet:
1. Gå till '...'
2. Klicka på '....'
3. Rulla ner till '....'
4. Se felet

**Förväntat beteende**
En klar och kortfattad beskrivning av vad du förväntade dig att hända.

**Skärmbilder**
Om det är tillämpligt, lägg till skärmbilder för att förklara ditt problem.

**Stationär dator (vänligen fyll i följande information):**
 - Webbläsare [t.ex. chrome, safari]

**Smartphone (vänligen fyll i följande information):**
 - Enhet: [t.ex. iPhone6]
 - OS: [t.ex. iOS8.1]
 - Webbläsare [t.ex. standard webbläsare, safari]

**Ytterligare sammanhang**
Lägg till annan kontext om problemet här.

**Comment by FredrikElliot** [comment]
Tog bort de andra två och kör bara på denna. Detta är nu överpushat på UAT så det går att testa. Vi jobbar fortfarande på att lösa den där grejen med att man inte får grönt meddelande (det är såklart inte det gröna meddelandet som det är fel på..), men hoppas kunna lösa det under nästa vecka. 

Nu går det också att förutspå namnen på driftstörningarn, så att man slipper skapa driftstörningar för att kunna se vad namnet blir. När man valt objekt visas namnet driftstörningen kommer få i titelrutan på första fliken. Själva namnsättningen är fortfarande inte hundra när det är olika nivåer och eventuellt behöver vi som sagt ta ett helhetsgrepp kring hur namnet sätt om framtida AOn kommer behöva olika djup i trädet. Det ska dock inte vara några problem om vi får in den strukturen på bryggor och linjer som vi pratade om på mötet i morse.

Vi fixar det nästa vecka! Trevlig helg!
@MonaAdawi @johulls

**Comment by MonaAdawi** [comment]
@FredrikElliot  Shit va bra med att man ser namnen i första steget nu! Jättebra :) 
Jag kan fortfarande inte avsluta störningar för Skärgårdstrafiken? Jag väljer sista statusen Åter i drift men den ligger kvar i listan och på hemsidan:
![image](https://github.com/studio27se/ehub/assets/164028902/bffa027f-67e6-444c-89ea-515f87750c77)

**Comment by FredrikElliot** [comment]
Hittade en liten bugg som vi åtgärdat! Det borde dock inte finnas två statusar i skärgårdstrafiken med samma flödesvärde. I vart fall inte för den lägsta statusen, eftersom det är det lägsta värdet som avgör "default" status.

Det blir fortfarande fel i utskicket av sms etc. vilket är anledningen till varför man inte får bekräftelse när man gör ändringar på ärendena. Vi har hittat felet (det har med delningen av miljöerna att göra), men inte lyckats åtgärda det problemet än. Dock sparas ändringarna som de ska ändå.

Det går nu bra att testa för detta felet ovan! :) @MonaAdawi

**Comment by MonaAdawi** [comment]
@FredrikElliot Nu kan jag avsluta störningar så den delen kan vi klarmarkera :)
@johulls får ändra nummer i flödet, jag tror jag sa samma sak eller frågade varför vissa hade samma nummer vid tillfälle :)
